### ISSUE TITLE
Unable to connect to Azure redis cluster [DATAREDIS-761]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1340]
**[Anand Kadu](https://jira.spring.io/secure/ViewProfile.jspa?name=anandkadu)** opened **[DATAREDIS-761](https://jira.spring.io/browse/DATAREDIS-761?redirect=false)** and commented

I am able to connect to Azure redis cluster using lettuce api statefulClusterConnection. But unable to connect using lettuceConnectionFactory using same credential.

One problem I notices in LettuceConnectionFactory, it make method private createRedisClient which prevent us to extend code.

getClusterConnection return spring's RedisClusterConnection to can't return lettuce specific connection

---

**Affects:** 1.8.9 (Ingalls SR9)

**Comment by meenarc** [comment]
I have a similar connectivity/socket timeout issue with spring ### data redis "LettuceConnectionFactory" usage to connect to Azure Redis
This issues doesn't show up when I see the basic lettuce-core API like RedisClient/RedisURI. So I know that this is not a basic network issue. Am using spring-data-redis 2.5.4  and lettuce-core 6.1.4.RELEASE  on JDK13

Basic code is

RedisStandaloneConfiguration redisConfig=new RedisStandaloneConfiguration("XXXXXXXXXX.redis.cache.windows.net", 6380);
        redisConfig.setPassword("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
         LettuceConnectionFactory factory = new LettuceConnectionFactory(redisConfig);
         factory.setValidateConnection(true);
         factory.afterPropertiesSet();

See exception below

00:05:14.963 [RedisSpringClient.main()] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
00:05:15.004 [RedisSpringClient.main()] DEBUG io.lettuce.core.resource.AddressResolverGroupProvider - Starting without optional netty's non-blocking DNS resolver library
00:05:15.007 [RedisSpringClient.main()] DEBUG io.lettuce.core.resource.DefaultClientResources - -Dio.netty.eventLoopThreads: 4
00:05:15.022 [RedisSpringClient.main()] DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider - Creating executor io.netty.util.concurrent.DefaultEventExecutorGroup
00:05:15.060 [RedisSpringClient.main()] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
00:05:15.061 [RedisSpringClient.main()] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
00:05:15.080 [RedisSpringClient.main()] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
00:05:15.080 [RedisSpringClient.main()] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
00:05:15.084 [RedisSpringClient.main()] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@4234e0dc
00:05:15.106 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
00:05:15.108 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
00:05:15.108 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 13
00:05:15.110 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
00:05:15.111 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
00:05:15.111 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
00:05:15.115 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: unavailable
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31)
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:227)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:109)
	at io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:218)
	at io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:197)
	at io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:179)
	at io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:163)
	at io.lettuce.core.resource.DefaultClientResources.<init>(DefaultClientResources.java:204)
	at io.lettuce.core.resource.DefaultClientResources$Builder.build(DefaultClientResources.java:639)
	at io.lettuce.core.resource.DefaultClientResources.create(DefaultClientResources.java:273)
	at io.lettuce.core.AbstractRedisClient.<init>(AbstractRedisClient.java:123)
	at io.lettuce.core.RedisClient.<init>(RedisClient.java:99)
	at io.lettuce.core.RedisClient.create(RedisClient.java:136)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.lambda$createClient$7(LettuceConnectionFactory.java:1084)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.createClient(LettuceConnectionFactory.java:1084)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.afterPropertiesSet(LettuceConnectionFactory.java:283)
	at RedisSpringClient.main(RedisSpringClient.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.base/java.lang.Thread.run(Thread.java:830)
00:05:15.117 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
00:05:15.119 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable
java.lang.IllegalAccessException: class io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @2b06dc12
	at java.base/jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:376)
	at java.base/java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:642)
	at java.base/java.lang.reflect.Method.invoke(Method.java:559)
	at io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:347)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:338)
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289)
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92)
	at io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:109)
	at io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:218)
	at io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:197)
	at io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:179)
	at io.netty.util.HashedWheelTimer.<init>(HashedWheelTimer.java:163)
	at io.lettuce.core.resource.DefaultClientResources.<init>(DefaultClientResources.java:204)
	at io.lettuce.core.resource.DefaultClientResources$Builder.build(DefaultClientResources.java:639)
	at io.lettuce.core.resource.DefaultClientResources.create(DefaultClientResources.java:273)
	at io.lettuce.core.AbstractRedisClient.<init>(AbstractRedisClient.java:123)
	at io.lettuce.core.RedisClient.<init>(RedisClient.java:99)
	at io.lettuce.core.RedisClient.create(RedisClient.java:136)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.lambda$createClient$7(LettuceConnectionFactory.java:1084)
	at java.base/java.util.Optional.orElseGet(Optional.java:362)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.createClient(LettuceConnectionFactory.java:1084)
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.afterPropertiesSet(LettuceConnectionFactory.java:283)
	at RedisSpringClient.main(RedisSpringClient.java:12)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.base/java.lang.Thread.run(Thread.java:830)
00:05:15.120 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
00:05:15.120 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
00:05:15.159 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent - maxDirectMemory: 4294967296 bytes (maybe)
00:05:15.160 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\a592255\AppData\Local\Temp (java.io.tmpdir)
00:05:15.160 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
00:05:15.162 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
00:05:15.162 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
00:05:15.164 [RedisSpringClient.main()] DEBUG io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
00:05:15.164 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
00:05:15.179 [RedisSpringClient.main()] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
00:05:15.210 [RedisSpringClient.main()] DEBUG reactor.util.Loggers$LoggerFactory - Using Slf4j logging framework
00:05:15.214 [RedisSpringClient.main()] DEBUG io.lettuce.core.event.jfr.EventRecorderHolder - Starting with JFR support
00:05:15.392 [RedisSpringClient.main()] DEBUG io.lettuce.core.resource.DefaultClientResources - LatencyUtils/HdrUtils are not available, metrics are disabled
00:05:15.550 [RedisSpringClient.main()] DEBUG io.lettuce.core.RedisClient - Trying to get a Redis connection for: redis://********************************************@prdccacheeastus2dev1.redis.cache.windows.net:6380
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 8
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 8
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.tinyCacheSize: 512
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
00:05:16.073 [RedisSpringClient.main()] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
00:05:16.083 [RedisSpringClient.main()] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
00:05:16.084 [RedisSpringClient.main()] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
00:05:16.084 [RedisSpringClient.main()] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
00:05:16.088 [RedisSpringClient.main()] DEBUG io.lettuce.core.resource.KqueueProvider - Starting without optional kqueue library
00:05:16.093 [RedisSpringClient.main()] DEBUG io.lettuce.core.resource.IOUringProvider - Starting without optional io_uring library
00:05:16.095 [RedisSpringClient.main()] DEBUG io.lettuce.core.resource.EpollProvider - Starting without optional epoll library
00:05:16.106 [RedisSpringClient.main()] DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider - Allocating executor io.netty.channel.nio.NioEventLoopGroup
00:05:16.106 [RedisSpringClient.main()] DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider - Creating executor io.netty.channel.nio.NioEventLoopGroup
00:05:16.108 [RedisSpringClient.main()] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
00:05:16.115 [RedisSpringClient.main()] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
00:05:16.116 [RedisSpringClient.main()] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
00:05:16.474 [RedisSpringClient.main()] DEBUG io.lettuce.core.resource.DefaultEventLoopGroupProvider - Adding reference to io.netty.channel.nio.NioEventLoopGroup@17b31f72, existing ref count 0
00:05:16.650 [RedisSpringClient.main()] DEBUG io.lettuce.core.RedisClient - Resolved SocketAddress prdccacheeastus2dev1.redis.cache.windows.net:6380 using redis://********************************************@prdccacheeastus2dev1.redis.cache.windows.net:6380
00:05:16.651 [RedisSpringClient.main()] DEBUG io.lettuce.core.AbstractRedisClient - Connecting to Redis at prdccacheeastus2dev1.redis.cache.windows.net:6380
00:05:16.688 [RedisSpringClient.main()] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 16292 (auto-detected)
00:05:16.691 [RedisSpringClient.main()] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
00:05:16.691 [RedisSpringClient.main()] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
00:05:16.856 [RedisSpringClient.main()] DEBUG io.netty.util.NetUtil - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
00:05:16.858 [RedisSpringClient.main()] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
00:05:16.988 [RedisSpringClient.main()] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 00:0d:3a:ff:fe:df:f3:fd (auto-detected)
00:05:17.065 [lettuce-nioEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0xa8334cc4, [id: 0x32d62306] (inactive), epid=0x1, chid=0x1] channelRegistered()
00:05:17.073 [lettuce-nioEventLoop-4-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
00:05:17.073 [lettuce-nioEventLoop-4-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxSharedCapacityFactor: 2
00:05:17.073 [lettuce-nioEventLoop-4-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.linkCapacity: 16
00:05:17.073 [lettuce-nioEventLoop-4-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
00:05:17.073 [lettuce-nioEventLoop-4-1] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.delayedQueue.ratio: 8
00:05:17.082 [lettuce-nioEventLoop-4-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
00:05:17.082 [lettuce-nioEventLoop-4-1] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
00:05:17.082 [lettuce-nioEventLoop-4-1] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@695262cd
00:05:17.145 [lettuce-nioEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0xa8334cc4, /10.250.12.242:60536 -> prdccacheeastus2dev1.redis.cache.windows.net/10.250.159.164:6380, epid=0x1, chid=0x1] write(ctx, AsyncCommand [type=HELLO, output=GenericMapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command], promise)
00:05:17.148 [lettuce-nioEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandEncoder - [channel=0xa8334cc4, /10.250.12.242:60536 -> prdccacheeastus2dev1.redis.cache.windows.net/10.250.159.164:6380] writing command AsyncCommand [type=HELLO, output=GenericMapOutput [output=null, error='null'], commandType=io.lettuce.core.protocol.Command]
00:06:17.122 [lettuce-nioEventLoop-4-1] DEBUG io.lettuce.core.AbstractRedisClient - Connecting to Redis at prdccacheeastus2dev1.redis.cache.windows.net:6380, initialization: prdccacheeastus2dev1.redis.cache.windows.net:6380
io.lettuce.core.RedisConnectionException: Connection closed prematurely
	at io.lettuce.core.protocol.RedisHandshakeHandler.channelInactive(RedisHandshakeHandler.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
	at io.lettuce.core.ChannelGroupListener.channelInactive(ChannelGroupListener.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:830)
00:06:17.123 [lettuce-nioEventLoop-4-1] DEBUG io.lettuce.core.RedisChannelHandler - closeAsync()
00:06:17.123 [lettuce-nioEventLoop-4-1] DEBUG io.lettuce.core.protocol.DefaultEndpoint - [unknown, epid=0x1] closeAsync()
00:06:17.126 [lettuce-nioEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0xa8334cc4, /10.250.12.242:60536 -> prdccacheeastus2dev1.redis.cache.windows.net/10.250.159.164:6380, epid=0x1, chid=0x1] channelInactive()
00:06:17.129 [lettuce-nioEventLoop-4-1] DEBUG io.lettuce.core.protocol.DefaultEndpoint - [unknown, epid=0x1] deactivating endpoint handler
00:06:17.133 [lettuce-nioEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0xa8334cc4, /10.250.12.242:60536 -> prdccacheeastus2dev1.redis.cache.windows.net/10.250.159.164:6380, epid=0x1, chid=0x1] channelInactive() done
[WARNING] 
org.springframework.data.redis.RedisConnectionFailureException: Unable to00:06:17.141 [lettuce-nioEventLoop-4-1] DEBUG io.lettuce.core.protocol.ConnectionWatchdog - [unknown, last known addr=null] chann elInactive()
00:06:17.141 [lettuce-nioEventLoop-4-1] DEBUcG io.lettuce.core.protocol.ConnectionWatchdog - [unknown, last known addr=null] ConnectionWatchdog not armed
00:06:17.141 [lettuce-nioEventLoop-4-1] DEBUG io.lettuce.core.protocol.CommandHandler - [channel=0xa8334cc4, /10.250.12.242:60536 -> prdccacheeastus2dev1.redis.cache.windows.net/10.250.159.164:6380, epid=0x1, chid=0x1] channelUnregistered()
onnect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to prdccacheeastus2dev1.redis.cache.windows.net:6380
    at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.translateException (LettuceConnectionFactory.java:1534)
    at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection (LettuceConnectionFactory.java:1442)
    at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection (LettuceConnectionFactory.java:1228)
    at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection (LettuceConnectionFactory.java:1211)
    at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection (LettuceConnectionFactory.java:975)
    at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection (LettuceConnectionFactory.java:360)
    at RedisSpringClient.main (RedisSpringClient.java:13)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:830)
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to prdccacheeastus2dev1.redis.cache.windows.net:6380
    at io.lettuce.core.RedisConnectionException.create (RedisConnectionException.java:78)
    at io.lettuce.core.RedisConnectionException.create (RedisConnectionException.java:56)
    at io.lettuce.core.AbstractRedisClient.getConnection (AbstractRedisClient.java:330)
    at io.lettuce.core.RedisClient.connect (RedisClient.java:216)
    at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.lambda$getConnection$1 (StandaloneConnectionProvider.java:115)
    at java.util.Optional.orElseGet (Optional.java:362)
    at org.springframework.data.redis.connection.lettuce.StandaloneConnectionProvider.getConnection (StandaloneConnectionProvider.java:115)
    at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection (LettuceConnectionFactory.java:1440)
    at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection (LettuceConnectionFactory.java:1228)
    at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection (LettuceConnectionFactory.java:1211)
    at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection (LettuceConnectionFactory.java:975)
    at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getConnection (LettuceConnectionFactory.java:360)
    at RedisSpringClient.main (RedisSpringClient.java:13)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run (ExecJavaMojo.java:282)
    at java.lang.Thread.run (Thread.java:830)
Caused by: io.lettuce.core.RedisConnectionException: Connection closed prematurely
    at io.lettuce.core.protocol.RedisHandshakeHandler.channelInactive (RedisHandshakeHandler.java:86)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive (AbstractChannelHandlerContext.java:241)
    at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive (ChannelInboundHandlerAdapter.java:81)
    at io.lettuce.core.ChannelGroupListener.channelInactive (ChannelGroupListener.java:69)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive (AbstractChannelHandlerContext.java:241)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive (DefaultChannelPipeline.java:1405)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:262)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive (AbstractChannelHandlerContext.java:248)
    at io.netty.channel.DefaultChannelPipeline.fireChannelInactive (DefaultChannelPipeline.java:901)
    at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run (AbstractChannel.java:818)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute (AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks (SingleThreadEventExecutor.java:472)
    at io.netty.channel.nio.NioEventLoop.run (NioEventLoop.java:500)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run (SingleThreadEventExecutor.java:989)
    at io.netty.util.internal.ThreadExecutorMap$2.run (ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run (FastThreadLocalRunnable.java:30)
    at java.lang.Thread.run (Thread.java:830)
00:06:17.221 [lettuce-nioEventLoop-4-1] DEBUG io.netty.channel.nio.NioEventLoop - Selector.select() returned prematurely because Thread.currentThread().interrupt() was called. Use NioEventLoop.shutdownGracefully() to shutdown the NioEventLoop.
[WARNING] thread Thread[lettuce-timer-3-1,5,RedisSpringClient] was interrupted but is still alive after waiting at least 14998msecs
[WARNING] thread Thread[lettuce-timer-3-1,5,RedisSpringClient] will linger despite being asked to die via interruption
[WARNING] thread Thread[lettuce-nioEventLoop-4-1,5,RedisSpringClient] will linger despite being asked to die via interruption
[WARNING] thread Thread[lettuce-eventExecutorLoop-1-1,5,RedisSpringClient] will linger despite being asked to die via interruption
`
