### ISSUE TITLE
Support ReactiveCrudRepository for Spring Data Redis Reactive [DATAREDIS-831]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1405]
**[Michael Gmeiner](https://jira.spring.io/secure/ViewProfile.jspa?name=gmeiner.m)** opened **[DATAREDIS-831](https://jira.spring.io/browse/DATAREDIS-831?redirect=false)** and commented

I do not find any support of using the RedisRepository feature with ReactiveCrudRepository. 

For example the following using:

```java
@Repository
interface BookRepo : ReactiveCrudRepository<Book, String>
```

with _@EnableRedisRepositories_ annotation present

and using default auto configuration from: spring-boot-starter-data-redis-reactive

I always get following error: 

```java
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [my.package.hash.Book] to type [reactor.core.publisher.Mono<?>]org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [my.package.hash.Book] to type [reactor.core.publisher.Mono<?>] at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321) at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:194) at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174) at org.springframework.data.repository.util.ReactiveWrapperConverters.toWrapper(ReactiveWrapperConverters.java:197) at org.springframework.data.repository.core.support.QueryExecutionResultHandler.postProcessInvocationResult(QueryExecutionResultHandler.java:126) at org.springframework.data.repository.core.support.QueryExecutionResultHandler.postProcessInvocationResult(QueryExecutionResultHandler.java:72) at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:580) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:99) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) at com.sun.proxy.$Proxy104.findById(Unknown Source) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:197) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) at com.sun.proxy.$Proxy104.findById(Unknown Source)
```

when calling for example:

```java
bookRepo.findById("harrypotter").subscribe { println(it) }
```

Am i doing something wrong or is it just not implemented yet as i do not find any documentation or examples on that? 

---

**Affects:** 2.0.7 (Kay SR7)

**Issue Links:**
- [DATAREDIS-796](https://jira.spring.io/browse/DATAREDIS-796) Does Spring Data Redis have plans to support Reactive Repositories?
 (_**"duplicates"**_)

7 votes, 8 watchers

**Comment by asarkar** [comment]
@markpollack @mp911de (not sure which username is correct)

Among other things, `@EnableRedisRepositories` has attributes to turn on keyspace notification events. While I've managed to get around the absence of reactive Redis repos, is there a way to enable the keyspace notifications from code? If you point me to the code that does this in Spring Data Redis, that'll be very helpful.

This is my reactive repo impl.
```
@Repository
class UuidRepository(
    private val redisTemplate: ReactiveRedisTemplate<String, Uuid>,
    private val objectMapper: ObjectMapper
) {
    private val reactiveValueOps = redisTemplate.opsForValue()
    suspend fun save(uuid: Uuid, ttl: Duration = Duration.ofSeconds(1L)): Boolean {
        return reactiveValueOps.setAndAwait(uuid.userId, uuid, ttl)
    }

    suspend fun findById(userId: String): Uuid? = reactiveValueOps.getAndAwait(userId)
}
```

**Comment by hantsy** [comment]
Any update to support Reactive repository?

**Comment by juliojgd** [comment]
@mp911de commented almost 4 years ago:
> we currently don't have plans to support reactive Redis repositories

Did plans regarding this evolved/changed during these (almost) 4 years?

Thanks in advance for the update on this

**Comment by Richardmbs12** [comment]
Any update on the roadmap please?

**Comment by mp911de** [comment]
Thanks for asking. With the recent development around Virtual Threads, the number of reasons to have reactive Redis repositories is shrinking to zero. Without Virtual Threads, scalability and non-blocking usage of repositories would have been a reason for a reactive API.

The implementation behind Redis Repositories bears a lot of complexity, requiring us to implement many infrastructure components and abstractions to avoid code duplications. Given Virtual Threads on the horizon, we rather recommend using imperative repositories running on Virtual Threads.

Repositories do not contribute any of the other reactive traits, such as backpressure or streaming support, that might be of interest in a reactive application arrangement.

Therefore, we decided to not implement this feature request.
