### ISSUE TITLE
Flaky Tests. [DATAREDIS-886]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1459]
**[Jens Schauder](https://jira.spring.io/secure/ViewProfile.jspa?name=schauder)** opened **[DATAREDIS-886](https://jira.spring.io/browse/DATAREDIS-886?redirect=false)** and commented

We are getting sporadic build failures on Travis (on 2.1.2, 2.1.x and 2.0.x)

 

```

Running org.springframework.data.redis.PropertyEditorsTestRunning org.springframework.data.redis.PropertyEditorsTestTests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.059 sec - in org.springframework.data.redis.PropertyEditorsTest2018-10-19 11:13:22,589 ERROR current.DefaultPromise.rejectedExecution: 181 - Failed to submit a listener notification task. Event loop shut down?java.util.concurrent.RejectedExecutionException: event executor terminated at io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:842) at io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:328) at io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:321) at io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:765) at io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:764) at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:432) at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:94) at io.netty.channel.group.DefaultChannelGroupFuture.setSuccess0(DefaultChannelGroupFuture.java:205) at io.netty.channel.group.DefaultChannelGroupFuture.<init>(DefaultChannelGroupFuture.java:121) at io.netty.channel.group.DefaultChannelGroup.close(DefaultChannelGroup.java:355) at io.netty.channel.group.DefaultChannelGroup.close(DefaultChannelGroup.java:222) at io.lettuce.core.AbstractRedisClient.shutdownAsync(AbstractRedisClient.java:411) at io.lettuce.core.AbstractRedisClient.shutdown(AbstractRedisClient.java:344) at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.destroy(LettuceConnectionFactory.java:266) at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:256) at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571) at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543) at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:954) at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504) at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:961) at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1039) at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1015) at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:935)\
```

---
No further details from [DATAREDIS-886](https://jira.spring.io/browse/DATAREDIS-886?redirect=false)

**Comment by mp911de** [comment]
This no longer seems to be an issue.
