### ISSUE TITLE
RedisCommandInterruptedException: Command interrupted after implementing connection pool [DATAREDIS-1016]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1582]
**[Pankaj Dubey](https://jira.spring.io/secure/ViewProfile.jspa?name=pankajad)** opened **[DATAREDIS-1016](https://jira.spring.io/browse/DATAREDIS-1016?redirect=false)** and commented

I'm using Redis Spring Data (`1.8.9.RELEASE`) with Lettuce (`4.5.0.Final`) as underlying Redis driver. I understand that Lettuce can share single connection with multiple thread but we have seen large no of connection (at one point we reached ~65 K connection) being created from client (From ~350 JVMs ) hence decided to use conenction pool. Since I'm using older version of Spring data Redis, I had to use DefaultLettucePool. After implementing the connection pool, I'm getting below error -
 

```java

@Bean
    public <T extends Serializable> RedisTemplate<String, Object> redisTemplate() {
        RedisTemplate<String, Object> redisTemplate = null;
        try {
            redisTemplate = new RedisTemplate<>();
            redisTemplate.setConnectionFactory(redisClusterConfiguration());
            redisTemplate.setKeySerializer(new StringRedisSerializer());
            redisTemplate.setValueSerializer(kryoRedisSerializer);
        } catch (Throwable t) {
            logger.error("Unable to create redisTemplate, returning null", t);
            redisTemplate = null;
        }
        logger.info("redisTemplate initialized successfully !!!");
        return redisTemplate;
    }

   @Bean
    public LettuceConnectionFactory redisConnectionFactory() {
        LettuceConnectionFactory lettuceConnectionFactory = null;
        try {
       lettuceConnectionFactory = new LettuceConnectionFactory(lettucePool());
            lettuceConnectionFactory.setUseSsl(true);
            lettuceConnectionFactory.setPassword("abc");
            lettuceConnectionFactory.setTimeout(200);
           lettuceConnectionFactory.setShutdownTimeout(1000);
            lettuceConnectionFactory.afterPropertiesSet();
            logger.info("lettuceConnectionFactory initialized successfully !!!");
        } catch(Throwable t) {
            logger.error("Unable to create redisConnectionFactory, returning null.", t);
            lettuceConnectionFactory=null;
        }
        return lettuceConnectionFactory;
    }

  @Bean
    public LettucePool lettucePool(){
        DefaultLettucePool lettucePool = new DefaultLettucePool(redis.dev, 6379, poolConfig());
        lettucePool.afterPropertiesSet();
        return lettucePool;
    }


   @Bean
    public GenericObjectPoolConfig poolConfig() {
        GenericObjectPoolConfig poolConfig = new GenericObjectPoolConfig();
        poolConfig.setMaxTotal(100);
        poolConfig.setMaxIdle(20);
        poolConfig.setBlockWhenExhausted(true);
        poolConfig.setMaxWaitMillis(10);    
        poolConfig.setTimeBetweenEvictionRunsMillis(5400000);        
        poolConfig.setSoftMinEvictableIdleTimeMillis(3600000);
        poolConfig.setMinIdle(10);
        return poolConfig;
    }
```

I'm getting the below error

```java
Caused by: com.lambdaworks.redis.RedisCommandInterruptedException: Command interrupted
    at com.lambdaworks.redis.protocol.AsyncCommand.await(AsyncCommand.java:86)
    at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:116)
    at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:96)
    at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:61)
    at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
    at com.sun.proxy.$Proxy309.get(Unknown Source)
    at org.springframework.data.redis.connection.lettuce.LettuceConnection.get(LettuceConnection.java:1296)
    ... 47 more
Caused by: java.lang.InterruptedException
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
    at com.lambdaworks.redis.protocol.AsyncCommand.await(AsyncCommand.java:82)1
```

 

---
No further details from [DATAREDIS-1016](https://jira.spring.io/browse/DATAREDIS-1016?redirect=false)

**Comment by dbses** [comment]
Is it a bug? How to solve it?

**Comment by Jashinck** [comment]
which version has solve it? @spring-projects-issues @mp911de
