### ISSUE TITLE
java.lang.Long cannot be cast to [B when doing HSCAN [DATAREDIS-1043]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-redis#1618]
**[bluecode2](https://jira.spring.io/secure/ViewProfile.jspa?name=bluecode2)** opened **[DATAREDIS-1043](https://jira.spring.io/browse/DATAREDIS-1043?redirect=false)** and commented

We got this exception when we do opsForHash().scan() operation using redisTemplate to Redis Cluster. We tried the same code for local redis and it works fine. For information, we are using Redis Cluster version 5.0.5

 

```java
java.lang.ClassCastException: java.lang.Long cannot be cast to [B
        at redis.clients.jedis.BinaryJedis.hscan(BinaryJedis.java:3391)
        at org.springframework.data.redis.connection.jedis.JedisHashCommands$1.doScan(JedisHashCommands.java:404)
        at org.springframework.data.redis.core.KeyBoundCursor.doScan(KeyBoundCursor.java:41)
        at org.springframework.data.redis.core.ScanCursor.scan(ScanCursor.java:88)
        at org.springframework.data.redis.core.ScanCursor.doOpen(ScanCursor.java:123)
        at org.springframework.data.redis.core.ScanCursor.open(ScanCursor.java:112)
        at org.springframework.data.redis.connection.jedis.JedisHashCommands.hScan(JedisHashCommands.java:414)
        at org.springframework.data.redis.connection.jedis.JedisHashCommands.hScan(JedisHashCommands.java:379)
        at org.springframework.data.redis.connection.DefaultedRedisConnection.hScan(DefaultedRedisConnection.java:987)
        at org.springframework.data.redis.core.DefaultHashOperations.lambda$scan$14(DefaultHashOperations.java:259)
        at org.springframework.data.redis.core.RedisTemplate.executeWithStickyConnection(RedisTemplate.java:374)
        at org.springframework.data.redis.core.DefaultHashOperations.scan(DefaultHashOperations.java:258)
        at com.example.mvc.controller.RedisController.getDataFromRedis(RedisController.java:376)
        at com.example.mvc.controller.RedisController.searchRedis(RedisController.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:286)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:260)
        at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:137)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:350)
        at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
        at weblogic.websocket.tyrus.TyrusServletFilter.doFilter(TyrusServletFilter.java:274)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
        at org.springframework.boot.web.servlet.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:118)
        at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:78)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3706)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3672)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:328)
        at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
        at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
        at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
        at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2443)
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2291)
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2269)
        at weblogic.servlet.internal.ServletRequestImpl.runInternal(ServletRequestImpl.java:1705)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1665)
        at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:272)
        at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
        at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
        at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
        at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
        at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:652)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)

```

 

Here's our pom.xml

 

```java
<dependency>
   <groupId>org.springframework.data</groupId> 
   <artifactId>spring-data-redis</artifactId> 
   <version>2.1.10.RELEASE</version> 
</dependency>
<dependency> 
   <groupId>redis.clients</groupId> 
   <artifactId>jedis</artifactId> 
   <version>2.9.0</version> 
   <type>jar</type> 
</dependency>
```

 

and here's our code

 

```java
// RedisTemplate Configuration
@Bean 
RedisConnectionFactory redisConnectionFactory() { 
   RedisStandaloneConfiguration redisStandaloneConfiguration = new RedisStandaloneConfiguration();
   redisStandaloneConfiguration.setHostName(REDIS_HOSTNAME); 
   redisStandaloneConfiguration.setPort(REDIS_PORT);
   redisStandaloneConfiguration.setPassword(REDIS_PASS); 
 
   JedisClientConfigurationBuilder jedisClientConfiguration = JedisClientConfiguration.builder();
   jedisClientConfiguration.connectTimeout(Duration.ofSeconds(60)).usePooling();  
   JedisConnectionFactory jedisConFactory = new JedisConnectionFactory(redisStandaloneConfiguration,jedisClientConfiguration.build()); 
   jedisConFactory.getPoolConfig().setMaxTotal(128); 
   jedisConFactory.getPoolConfig().setBlockWhenExhausted(false);    
   return jedisConFactory; 
}

@Bean 
public RedisTemplate<String, Object> redisTemplate() { 
   RedisTemplate<String, Object> template = new RedisTemplate<>(); 
   template.setConnectionFactory(redisConnectionFactory()); 
   template.setDefaultSerializer(new StringRedisSerializer()); 
   template.setHashKeySerializer(new GenericJackson2JsonRedisSerializer()); 
   template.setEnableTransactionSupport(true); 
   return template; 
}
```

```java
 // Do HSCAN
try { 
   Cursor<Entry<Object, Object>> cursorMap = redisTemplate.opsForHash().scan(mainKey, ScanOptions.scanOptions()
                                                                       .match(pattern)
                                                                       .count(10000).build()); 
   if (cursorMap != null) { 
      while (cursorMap.hasNext()) { 
         Entry<Object, Object> entry = cursorMap.next(); 
         lstKey.add(entry.getKey().toString()); 
         lstValue.add(entry.getValue().toString()); 
      } 
   } 
} catch (Exception e) { 
   e.printStackTrace(); 
   throw e; 
}
```

 

Any idea how to fix it? 

 

 

---
No further details from [DATAREDIS-1043](https://jira.spring.io/browse/DATAREDIS-1043?redirect=false)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
