### ISSUE TITLE
RedisTemplate happened thread-unsafe case,maybe my code worng but i'dnot know where and why [DATAREDIS-1044]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-data-redis#1619]
**[Jianhui](https://jira.spring.io/secure/ViewProfile.jspa?name=spring4me)** opened **[DATAREDIS-1044](https://jira.spring.io/browse/DATAREDIS-1044?redirect=false)** and commented

i try use RedisTemplate to implement a distributed lock, then i got some exception it's seem like thread-unsafe case.

java.lang.ClassCastException: java.lang.Long cannot be cast to [B
        at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:181) ~[jedis-2.6.2.jar:?]
        at redis.clients.jedis.Jedis.set(Jedis.java:79) ~[jedis-2.6.2.jar:?]
        at com.xxx.locks.DistributedLock$1.doInRedis(DistributedLock.java:45) ~[fop-pdbds-core-baseinfo-common-1.0-SNAPSHOT.jar:?]
        at com.xxx.baseinfo.locks.DistributedLock$1.doInRedis(DistributedLock.java:39) ~[fop-pdbds-core-baseinfo-common-1.0-SNAPSHOT.jar:?]
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:190) ~[spring-data-redis-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:152) ~[spring-data-redis-1.4.2.RELEASE.jar:1.4.2.RELEASE]
        at com.xxx.locks.DistributedLock.lock(DistributedLock.java:39) [fop-pdbds-core-baseinfo-common-1.0-SNAPSHOT.jar:?]
        at com.xxx.kafka.consumer.EmployeeDataConsumerListener.onMessage(EmployeeDataConsumerListener.java:70) [fop-pdbds-core-baseinfo-service-1.0-SNAPSHOT.jar:?]
        at com.sf.kafka.api.consume.KafkaConsumer$ConsumeTask.run(KafkaConsumer.java:247) [sf-kafka-api-core-1.15.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172-ea]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172-ea]

code:

public boolean lock(String key, String requestId) {
        String lockResult = "";
        try {
            lockResult = (String) iRedisCache.getRedisTemplate().execute(new RedisCallback\<String>() {
                `@Override`
                public String doInRedis(RedisConnection redisConnection) {
                    Object nativeConnection = redisConnection.getNativeConnection();
                    String result = "";
                    if (nativeConnection instanceof JedisCommands) {
                        result = ((JedisCommands) nativeConnection).set(key, requestId, "NX", "EX",
                                DISTRIBUTEDLOCK_TIME);
                    }
                    return result;
                }
            }, true);
        } catch (Exception e) {
          
        }
        return "OK".equals(lockResult);
    }
    public void releaseLock(String key, String requestId) {
        try {
            iRedisCache.getRedisTemplate().execute(new RedisCallback\<String>() {
                `@Override`
                public String doInRedis(RedisConnection redisConnection) {
                    Jedis jedis = (Jedis) redisConnection.getNativeConnection();
                    final String script = "if redis.call(\"get\",\"" + key + "\") == \"" + requestId + "\"then  " +
                            "return redis.call(\"del\",\"" + key + "\") else return 0 end ";
                    Long effectRows = (Long) jedis.eval(script);
                    return "OK";
                }
            }, true);
        } catch (Exception e) {
           
        }
    }

thks

---

**Affects:** 1.8.23 (Ingalls SR23)

**Comment by spring-issuemaster** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
