### ISSUE TITLE
Add support for `ZPOPMIN` and `ZPOPMAX` commands including blocking variants

### ISSUE THREAD

**Issue by max-end** [spring-projects/spring-data-redis#2007]
redisTemplate is  not suport zpopmin、zpopmax  instructions?

**Comment by mp911de** [comment]
Thanks for reaching out. We're happy to review a pull request that introduces this functionality. Until then you can use `RedisConnection.execute(…)` to call Redis commands yourself that aren't exposed through a Java method.

**Comment by max-end** [comment]
> Thanks for reaching out. We're happy to review a pull request that introduces this functionality. Until then you can use `RedisConnection.execute(…)` to call Redis commands yourself that aren't exposed through a Java method.

Can you help me? thank you


`         RedisConnection redisConnection=redisTemplate.getRequiredConnectionFactory().getConnection();
        Object o = redisConnection.execute("zpopmin","TESTLIST".getBytes());`


java.lang.IllegalStateException: io.lettuce.core.output.ByteArrayOutput does not support set(double)

	at io.lettuce.core.output.CommandOutput.set(CommandOutput.java:118)
	at io.lettuce.core.protocol.RedisStateMachine.safeSet(RedisStateMachine.java:794)
	at io.lettuce.core.protocol.RedisStateMachine.handleFloat(RedisStateMachine.java:426)
	at io.lettuce.core.protocol.RedisStateMachine$State$Type.handle(RedisStateMachine.java:206)
	at io.lettuce.core.protocol.RedisStateMachine.doDecode(RedisStateMachine.java:334)
	at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:295)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:832)
	at io.lettuce.core.protocol.CommandHandler.decode0(CommandHandler.java:783)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:766)
	at io.lettuce.core.protocol.CommandHandler.decode(CommandHandler.java:649)
	at io.lettuce.core.protocol.CommandHandler.channelRead(CommandHandler.java:589)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mp911de** [comment]
When using Lettuce, you need to provide a `CommandOutput` to capture the Redis response. For `[B]ZPOP[MIN|MAX]` that's `new ScoredValueOutput<>(ByteArrayCodec.INSTANCE)` (via `execute(String command, @Nullable CommandOutput commandOutputTypeHint, byte[]... args)`).

Spring Data Redis doesn't have yet command output hints for these commands.

**Comment by poeschko** [comment]
Very nice to get support for these commands! Any idea yet when this will be available in a released version?
