### ISSUE TITLE
NullPointException when calling addMessageListener on Jedis Cluster

### ISSUE THREAD

**Issue by InfoGG** [spring-projects/spring-data-redis#2020]
I'm using spring-data-redis 2.2.11-RELEASE.

This is my test usecase:

```
    @Test
    public void bugTest() throws InterruptedException {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate();
        JedisConnectionFactory jedisConnectionFactory;
        RedisClusterConfiguration redisClusterConfiguration = new RedisClusterConfiguration();

        List<RedisNode> list = new ArrayList<>();
        list.add(new RedisNode("127.0.0.1", 11001));
        list.add(new RedisNode("127.0.0.1", 11002));
        list.add(new RedisNode("127.0.0.1", 11003));
        list.add(new RedisNode("127.0.0.1", 11004));
        list.add(new RedisNode("127.0.0.1", 11005));
        list.add(new RedisNode("127.0.0.1", 11006));

        redisClusterConfiguration.setClusterNodes(list);
        redisClusterConfiguration.setMaxRedirects(8);
        jedisConnectionFactory = new JedisConnectionFactory(redisClusterConfiguration);
        jedisConnectionFactory.afterPropertiesSet();
        redisTemplate.setConnectionFactory(jedisConnectionFactory);
        redisTemplate.afterPropertiesSet();

        RedisMessageListenerContainer container = new RedisMessageListenerContainer();
        container.setConnectionFactory(redisTemplate.getConnectionFactory());
        container.afterPropertiesSet();
        container.start();

        MessageListenerAdapter messageListenerAdapter = new MessageListenerAdapter();

        for (int i = 1; i < 100; i++) {
            Thread.sleep(2);
            container.addMessageListener(messageListenerAdapter, new ChannelTopic(i + "a"));
            container.addMessageListener(messageListenerAdapter, new ChannelTopic(i + "b"));
            container.addMessageListener(messageListenerAdapter, new ChannelTopic(i + "c"));
        }
    }

```

It will cause NullPointException.

This is the stacktrace:

```
java.lang.NullPointerException
	at redis.clients.jedis.BinaryJedisPubSub.subscribe(BinaryJedisPubSub.java:48)
	at org.springframework.data.redis.connection.jedis.JedisSubscription.doSubscribe(JedisSubscription.java:81)
	at org.springframework.data.redis.connection.util.AbstractSubscription.subscribe(AbstractSubscription.java:185)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer$SubscriptionTask.subscribeChannel(RedisMessageListenerContainer.java:909)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.addListener(RedisMessageListenerContainer.java:542)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.addMessageListener(RedisMessageListenerContainer.java:383)
	at org.springframework.data.redis.listener.RedisMessageListenerContainer.addMessageListener(RedisMessageListenerContainer.java:395)
	at io.iec.edp.caf.commons.layeringcache.config.LayeringCacheTest.bugTest(LayeringCacheTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

I've debugged the source code, and I found in **BinaryJedisPubSub.subscribe()**, **BinaryJedisPubSub.client** is null.

![image](https://user-images.githubusercontent.com/9886683/112974493-1db4d400-9185-11eb-8306-ff55817a568b.png)
![image](https://user-images.githubusercontent.com/9886683/112974737-5c4a8e80-9185-11eb-915d-c44d4ac56d6c.png)

Look at this method:  **RedisMessageListenerContainer$SubscriptionTask.subscribeChannel():909**
![image](https://user-images.githubusercontent.com/9886683/112974360-f3fbad00-9184-11eb-99fa-d1f402ae83e3.png)

It will check **connection.subscription** before calling.

```
```

**connection.subscription** and **BinaryJedisPubSub.client** are initialized in another thread: _RedisMessageListenerContainer_

This is the stacktrace:
![image](https://user-images.githubusercontent.com/9886683/112965068-7ed7aa00-917b-11eb-849b-84f7e2425e59.png)

**BinaryJedisPubSub.client**  is intialized in **BinaryJedisPubSub.proceed():79**
![image](https://user-images.githubusercontent.com/9886683/113100581-2ad9cd80-922e-11eb-9277-8e44b19d7fc0.png)

**connection.subscription**  is intialized in **JedisClusterConnection.subscribe():445**
![image](https://user-images.githubusercontent.com/9886683/112966629-fd811700-917c-11eb-8738-7552185cf38d.png)

We can see **connection.subscription** is initialized just a little before **BinaryJedisPubSub.client** .

So I guess this exception happens because when the _main thread_ calls **RedisMessageListenerContainer$SubscriptionTask.subscribeChannel()**,
the thread _RedisMessageListenerContainer_ has finished the initialization of **connection.subscription**, but hasn't initialzed **BinaryJedisPubSub.client**.

Please fix this , thanks!

**Comment by mp911de** [comment]
That is a duplicate of #1980
