### ISSUE TITLE
FindByIndexNameSessionRepository.findByPrincipalName() fails with org.springframework.data.redis.serializer.SerializationException

### ISSUE THREAD

**Issue by lin007hypr** [spring-projects/spring-data-redis#2072]
Hi,

Trying to get the session and failing with:

```
org.springframework.data.redis.serializer.SerializationException: Cannot deserialize; nested exception is org.springframework.core.serializer.support.SerializationFailedException: Failed to deserialize payload. Is the byte array a result of corresponding serialization for DefaultDeserializer?; nested exception is java.io.StreamCorruptedException: invalid stream header: 35303064|	
at org.springframework.data.redis.serializer.JdkSerializationRedisSerializer.deserialize(JdkSerializationRedisSerializer.java:84)|
at org.springframework.data.redis.serializer.SerializationUtils.deserializeValues(SerializationUtils.java:54)|	
at org.springframework.data.redis.serializer.SerializationUtils.deserialize(SerializationUtils.java:62)|	
at org.springframework.data.redis.core.AbstractOperations.deserializeValues(AbstractOperations.java:223)|	
at org.springframework.data.redis.core.DefaultSetOperations.members(DefaultSetOperations.java:216)|	
at org.springframework.data.redis.core.DefaultBoundSetOperations.members(DefaultBoundSetOperations.java:152)|	
at org.springframework.session.data.redis.RedisIndexedSessionRepository.findByIndexNameAndIndexValue(RedisIndexedSessionRepository.java:421)|	
at org.springframework.session.FindByIndexNameSessionRepository.findByPrincipalName(FindByIndexNameSessionRepository.java:68)|
```

**Comment by christophstrobl** [comment]
This is the issue tracker of Spring Data Redis. You're looking for [spring-projects/spring-session](https://github.com/spring-projects/spring-session). Please open an issue there.
