### ISSUE TITLE
When i update spring.redis.cluster.nodes config but its inoperative.

### ISSUE THREAD

**Issue by CarlosZzzz** [spring-projects/spring-data-redis#2073]
The old config of spring.redis.cluster.nodes is
192.168.100.102:6380
192.168.100.102:6381
192.168.100.102:6382
192.168.100.102:6383
192.168.100.102:6384
192.168.100.102:6385

The new config is:
192.168.100.100:6380
192.168.100.100:6381
192.168.100.100:6382
192.168.100.100:6383
192.168.100.100:6384
192.168.100.100:6385

The application log is:

> 2021-05-28 15:09:56.207  INFO 83761 --- [           main] com.tzwy.icsmas.event.EventApplication   : Starting EventApplication using Java 14.0.2 on fangzhoudeMacBook-Pro.local with PID 83761 (/Users/fangzhou/IdeaProjects/icsmas/event/target/classes started by fangzhou in /Users/fangzhou/IdeaProjects/icsmas)
2021-05-28 15:09:56.210  INFO 83761 --- [           main] com.tzwy.icsmas.event.EventApplication   : No active profile set, falling back to default profiles: default
2021-05-28 15:09:56.817  INFO 83761 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2021-05-28 15:09:56.819  INFO 83761 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data Redis repositories in DEFAULT mode.
2021-05-28 15:09:56.836  INFO 83761 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 8 ms. Found 0 Redis repository interfaces.
2021-05-28 15:09:57.315  INFO 83761 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-05-28 15:09:57.322  INFO 83761 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-05-28 15:09:57.323  INFO 83761 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.41]
2021-05-28 15:09:57.413  INFO 83761 --- [           main] o.a.c.c.C.[.[localhost].[/icsmas/event]  : Initializing Spring embedded WebApplicationContext
2021-05-28 15:09:57.413  INFO 83761 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1163 ms
2021-05-28 15:09:57.809  INFO 83761 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService
2021-05-28 15:09:59.534  WARN 83761 --- [ueEventLoop-4-8] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [192.168.100.102/<unresolved>:6381]: finishConnect(..) failed: Connection refused: /192.168.100.102:6381
2021-05-28 15:09:59.534  WARN 83761 --- [ueEventLoop-4-1] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [192.168.100.102/<unresolved>:6382]: finishConnect(..) failed: Connection refused: /192.168.100.102:6382
2021-05-28 15:09:59.534  WARN 83761 --- [ueEventLoop-4-3] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [192.168.100.102/<unresolved>:6384]: finishConnect(..) failed: Connection refused: /192.168.100.102:6384
2021-05-28 15:09:59.534  WARN 83761 --- [ueEventLoop-4-7] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [192.168.100.102/<unresolved>:6380]: finishConnect(..) failed: Connection refused: /192.168.100.102:6380
2021-05-28 15:09:59.534  WARN 83761 --- [ueEventLoop-4-4] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [192.168.100.102/<unresolved>:6385]: finishConnect(..) failed: Connection refused: /192.168.100.102:6385
2021-05-28 15:09:59.534  WARN 83761 --- [ueEventLoop-4-2] i.l.c.c.t.DefaultClusterTopologyRefresh  : Unable to connect to [192.168.100.102/<unresolved>:6383]: finishConnect(..) failed: Connection refused: /192.168.100.102:6383
2021-05-28 15:10:00.134  WARN 83761 --- [ueEventLoop-4-5] i.l.core.cluster.RedisClusterClient      : finishConnect(..) failed: Connection refused: /192.168.100.102:6385
2021-05-28 15:10:00.624  WARN 83761 --- [ueEventLoop-4-6] i.l.core.cluster.RedisClusterClient      : finishConnect(..) failed: Connection refused: /192.168.100.102:6381
2021-05-28 15:10:02.530  WARN 83761 --- [ueEventLoop-4-7] i.l.core.cluster.RedisClusterClient      : finishConnect(..) failed: Connection refused: /192.168.100.102:6383
2021-05-28 15:10:03.148  WARN 83761 --- [ueEventLoop-4-8] i.l.core.cluster.RedisClusterClient      : finishConnect(..) failed: Connection refused: /192.168.100.102:6382
2021-05-28 15:10:03.632  WARN 83761 --- [ueEventLoop-4-1] i.l.core.cluster.RedisClusterClient      : finishConnect(..) failed: Connection refused: /192.168.100.102:6384
2021-05-28 15:10:04.507  WARN 83761 --- [ueEventLoop-4-2] i.l.core.cluster.RedisClusterClient      : finishConnect(..) failed: Connection refused: /192.168.100.102:6380
2021-05-28 15:10:04.517  WARN 83761 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sensorServiceImpl': Unsatisfied dependency expressed through field 'baseMapper'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sensorMapper' defined in file [/Users/fangzhou/IdeaProjects/icsmas/event/target/classes/com/tzwy/icsmas/event/dao/SensorMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [com/baomidou/mybatisplus/autoconfigure/MybatisPlusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.apache.ibatis.session.SqlSessionFactory]: Factory method 'sqlSessionFactory' threw exception; nested exception is org.springframework.core.NestedIOException: Failed to parse mapping resource: 'file [/Users/fangzhou/IdeaProjects/icsmas/event/target/classes/mapper/SensorMapper.xml]'; nested exception is org.apache.ibatis.builder.BuilderException: Error parsing Mapper XML. The XML location is 'file [/Users/fangzhou/IdeaProjects/icsmas/event/target/classes/mapper/SensorMapper.xml]'. Cause: org.apache.ibatis.cache.CacheException: Could not instantiate cache implementation (class com.tzwy.icsmas.event.manager.redis.cache.PerpetualCache). Cause: java.lang.reflect.InvocationTargetException
2021-05-28 15:10:04.630  INFO 83761 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService
2021-05-28 15:10:04.630  INFO 83761 --- [           main] .c.NacosValueAnnotationBeanPostProcessor : class com.alibaba.nacos.spring.context.annotation.config.NacosValueAnnotationBeanPostProcessor was destroying!
2021-05-28 15:10:04.631  INFO 83761 --- [           main] AnnotationNacosInjectedBeanPostProcessor : class com.alibaba.nacos.spring.beans.factory.annotation.AnnotationNacosInjectedBeanPostProcessor was destroying!
2021-05-28 15:10:04.633  INFO 83761 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
Caused by: org.springframework.data.redis.RedisConnectionFailureException: Redis connection failed; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to [redis://******@192.168.100.100:6380, redis://******@192.168.100.100:6381, redis://******@192.168.100.100:6382, redis://******@192.168.100.100:6383, redis://******@192.168.100.100:6384, redis://******@192.168.100.100:6385]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:66) ~[spring-data-redis-2.4.2.jar:2.4.2]
	at org.springframework.data.redis.connection.lettuce.LettuceFutureUtils.join(LettuceFutureUtils.java:74) ~[spring-data-redis-2.4.2.jar:2.4.2]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionProvider.getConnection(LettuceConnectionProvider.java:53) ~[spring-data-redis-2.4.2.jar:2.4.2]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$ExceptionTranslatingConnectionProvider.getConnection(LettuceConnectionFactory.java:1459) ~[spring-data-redis-2.4.2.jar:2.4.2]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getNativeConnection(LettuceConnectionFactory.java:1247) ~[spring-data-redis-2.4.2.jar:2.4.2]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory$SharedConnection.getConnection(LettuceConnectionFactory.java:1230) ~[spring-data-redis-2.4.2.jar:2.4.2]
	at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getClusterConnection(LettuceConnectionFactory.java:378) ~[spring-data-redis-2.4.2.jar:2.4.2]
	at com.tzwy.icsmas.event.manager.redis.cache.PerpetualCache.<init>(PerpetualCache.java:23) ~[classes/:na]
	... 70 common frames omitted
Caused by: io.lettuce.core.RedisConnectionException: Unable to connect to [redis://******@192.168.100.100:6380, redis://******@192.168.100.100:6381, redis://******@192.168.100.100:6382, redis://******@192.168.100.100:6383, redis://******@192.168.100.100:6384, redis://******@192.168.100.100:6385]
	at io.lettuce.core.RedisConnectionException.create(RedisConnectionException.java:78) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
	at io.lettuce.core.cluster.RedisClusterClient.lambda$transformAsyncConnectionException$40(RedisClusterClient.java:1146) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
	at io.lettuce.core.DefaultConnectionFuture.lambda$thenCompose$1(DefaultConnectionFuture.java:253) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[na:na]
	at reactor.core.publisher.MonoToCompletableFuture.onError(MonoToCompletableFuture.java:76) ~[reactor-core-3.4.1.jar:3.4.1]
	at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onError(FluxMapFuseable.java:140) ~[reactor-core-3.4.1.jar:3.4.1]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:234) ~[reactor-core-3.4.1.jar:3.4.1]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:172) ~[reactor-core-3.4.1.jar:3.4.1]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.4.1.jar:3.4.1]
	at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258) ~[reactor-core-3.4.1.jar:3.4.1]
	at reactor.core.publisher.MonoCompletionStage.lambda$subscribe$0(MonoCompletionStage.java:76) ~[reactor-core-3.4.1.jar:3.4.1]
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2152) ~[na:na]
	at io.lettuce.core.AbstractRedisClient.lambda$initializeChannelAsync0$4(AbstractRedisClient.java:405) ~[lettuce-core-6.0.1.RELEASE.jar:6.0.1.RELEASE]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.fulfillConnectPromise(AbstractKQueueChannel.java:623) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.finishConnect(AbstractKQueueChannel.java:642) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.shutdownInput(AbstractKQueueChannel.java:450) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readEOF(AbstractKQueueChannel.java:487) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:213) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:289) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /192.168.100.102:6380
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
	at io.netty.channel.unix.Errors.throwConnectException(Errors.java:124) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.unix.Socket.finishConnect(Socket.java:251) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.doFinishConnect(AbstractKQueueChannel.java:656) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.finishConnect(AbstractKQueueChannel.java:636) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.shutdownInput(AbstractKQueueChannel.java:450) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readEOF(AbstractKQueueChannel.java:487) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:213) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:289) ~[netty-all-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.55.Final.jar:4.1.55.Final]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]

**Comment by CarlosZzzz** [comment]
I knew thats why, because i implements mybatis cache interface and hold a redis cluster connection object so old config was saved

**Comment by christophstrobl** [comment]
I'm sorry but the given information is insufficient. Please provide [more details](https://stackoverflow.com/help/how-to-ask) about the problem.

**Comment by CarlosZzzz** [comment]
I solved the problem, please close the issue

**Comment by christophstrobl** [comment]
Thanks for letting us know!
