### ISSUE TITLE
StreamPollTask.deserializeAndEmitRecords NPE

### ISSUE THREAD

**Issue by wywanchongshan** [spring-projects/spring-data-redis#2147]
spring boot data redis pom dependency:
```pom
<dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.5.4</version>
                <type>pom</type>
                <scope>import</scope>
 </dependency>

<dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-data-redis</artifactId>
 </dependency>
```
redis yaml
```yml
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis@test
    database: 0
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
```

RedisStreamConfig
```java
@Slf4j
@Configuration
public class RedisStreamConfig {

    public static final String   REDIS_STREM_NAME          = "shopMsgStream";

    public static final String   REDIS_STREM_CONSUME_GROUP = "shopMsgConsumerGroup";

    @Autowired
    private RedisMessageListener redisMessageListener;

    @Autowired
    ThreadPoolTaskExecutor       threadPoolTaskExecutor;

    @Autowired
    private StringRedisTemplate  stringRedisTemplate;

    @Bean
    public Subscription subscription(RedisConnectionFactory factory) throws UnknownHostException {

        StreamMessageListenerContainer.StreamMessageListenerContainerOptions<String, MapRecord<String, String, String>> options = StreamMessageListenerContainer.StreamMessageListenerContainerOptions
            .builder().pollTimeout(Duration.ofSeconds(1)).batchSize(20)
            .errorHandler(new ErrorHandler() {
                @Override
                public void handleError(Throwable t) {
                    LogUtil.error(RedisStreamConfig.log, t, "消息处理异常");
                }
            }).executor(this.threadPoolTaskExecutor).serializer(new StringRedisSerializer())
            .build();

        // 创建一个stream 监听容器对象
        StreamMessageListenerContainer<String, MapRecord<String, String, String>> listenerContainer = StreamMessageListenerContainer
            .create(factory, options);

        // 创建消费者
        Consumer consumer = Consumer.from(RedisStreamConfig.REDIS_STREM_CONSUME_GROUP,
            InetAddress.getLocalHost().getHostName());
        // 指定消费最新的消息
        StreamOffset<String> offset = StreamOffset.create(RedisStreamConfig.REDIS_STREM_NAME,
            ReadOffset.lastConsumed());

        // 创建一个新订阅,不需要自动ack确认,需要手动确认
        Subscription subscription = listenerContainer.receive(consumer, offset,
            this.redisMessageListener);

        //        StreamMessageListenerContainer.StreamReadRequest<String> streamReadRequest = StreamMessageListenerContainer.StreamReadRequest
        //            .builder(offset)
        //            .errorHandler((error) -> RedisStreamConfig.log.error(error.getMessage()))
        //            .cancelOnError(e -> false).consumer(consumer)
        //            //关闭自动ack确认
        //            .autoAcknowledge(false).build();
        //
        //        listenerContainer.register(streamReadRequest, this.redisMessageListener);

        listenerContainer.start();
        return subscription;

    }
}
```

When there is no data in redis stream , it will report to NPE 

```
2021-08-23 16:15:18.357 [task-1] -19000[]DEBUG org.redisson.command.RedisExecutor -acquired connection for command (XREADGROUP) and params [GROUP, shopMsgConsumerGroup, LAPTOP-M9KTTVAV, COUNT, 20, BLOCK, 1000, STREAMS, [115, 104, 111, 112, 77, 115, 103, 83, 116, 114, ...], >] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using node /127.0.0.1:6379... RedisConnection@1921355759 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x29a32a46, L:/127.0.0.1:51669 - R:/127.0.0.1:6379], currentCommand=null]
2021-08-23 16:15:18.858 [redisson-netty-2-20] -19000[]DEBUG org.redisson.connection.DNSMonitor -Request sent to resolve ip address for master host: 127.0.0.1
2021-08-23 16:15:18.860 [redisson-netty-2-19] -19000[]DEBUG org.redisson.connection.DNSMonitor -Resolved ip: /127.0.0.1 for master host: 127.0.0.1
2021-08-23 16:15:18.913 [main ] -19000[]INFO  s.d.s.w.PropertySourcedRequestMappingHandlerMapping -Mapped URL path [/v2/api-docs] onto method [springfox.documentation.swagger2.web.Swagger2Controller#getDocumentation(String, HttpServletRequest)]
2021-08-23 16:15:19.343 [main ] -19000[]DEBUG o.s.d.redis.listener.RedisMessageListenerContainer -Postpone listening for Redis messages until actual listeners are added
2021-08-23 16:15:19.344 [main ] -19000[]DEBUG o.s.d.redis.listener.RedisMessageListenerContainer -Started RedisMessageListenerContainer
2021-08-23 16:15:19.397 [redisson-timer-4-1] -19000[]DEBUG org.redisson.command.RedisExecutor -connection released for command (XREADGROUP) and params [GROUP, shopMsgConsumerGroup, LAPTOP-M9KTTVAV, COUNT, 20, BLOCK, 1000, STREAMS, [115, 104, 111, 112, 77, 115, 103, 83, 116, 114, ...], >] from slot NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null] using connection RedisConnection@1921355759 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x29a32a46, L:/127.0.0.1:51669 - R:/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@7cde2f5c(success)], command=(XREADGROUP), params=[GROUP, shopMsgConsumerGroup, LAPTOP-M9KTTVAV, COUNT, 20, BLOCK, 1000, STREAMS, [115, 104, 111, 112, 77, 115, 103, 83, 116, 114, ...], >], codec=org.redisson.client.codec.ByteArrayCodec]]
2021-08-23 16:15:19.397 [task-1] -19000[]DEBUG o.s.data.redis.core.RedisConnectionUtils -Closing Redis Connection.
2021-08-23 16:15:19.398 [redisson-netty-2-6] -19000[]DEBUG org.redisson.client.handler.ConnectionWatchdog -reconnecting RedisConnection@1921355759 [redisClient=[addr=redis://127.0.0.1:6379], channel=[id: 0x29a32a46, L:/127.0.0.1:51669 ! R:/127.0.0.1:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@7cde2f5c(success)], command=(XREADGROUP), params=[GROUP, shopMsgConsumerGroup, LAPTOP-M9KTTVAV, COUNT, 20, BLOCK, 1000, STREAMS, [115, 104, 111, 112, 77, 115, 103, 83, 116, 114, ...], >], codec=org.redisson.client.codec.ByteArrayCodec]] to /127.0.0.1:6379 
2021-08-23 16:15:19.401 [task-1] -19000[]ERROR xxxconfig.RedisStreamConfig -[164][消息处理异常]
java.lang.NullPointerException: null
	at org.springframework.data.redis.stream.StreamPollTask.deserializeAndEmitRecords(StreamPollTask.java:171)
	at org.springframework.data.redis.stream.StreamPollTask.doLoop(StreamPollTask.java:148)
	at org.springframework.data.redis.stream.StreamPollTask.run(StreamPollTask.java:132)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mp911de** [comment]
Redisson's Spring Data Redis connector is maintained at their [own repository](https://github.com/redisson/redisson). From the exception message, Redisson returns `null` instead of an empty list if there is no data. Please ask the Redisson maintainer to return always empty lists instead of `null` if the response is empty to fix that issue.
