### ISSUE TITLE
Eager initialization of `LettuceConnectionFactory` configured for Redis Cluster causes `ClassCastException`

### ISSUE THREAD

**Issue by sangeethaPrem** [spring-projects/spring-data-redis#2186]
Hi,

 

When I try to call the initConnection() on my clustered redis, i get the error java.lang.ClassCastException: io.lettuce.core.cluster.StatefulRedisClusterConnectionImpl cannot be cast to io.lettuce.core.api.StatefulRedisConnection

                at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:975)

 

looking at the code it seems like the class cast is only for the StatefulRedisConnection, where as the validateConnection() supports both StatefulRedisConnection and StatefulRedisClusterConnection.

 

any one faced this before? on how to achieve this?
We are doing lazy initialisation to the redis cluster.
Please help.
 

Thanks.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal sample](https://stackoverflow.com/help/mcve) that reproduces the problem.

**Comment by aronica** [comment]
@mp911de 
I encounter this issue here, you only need to enable eagerInitialization while configure Bean LettuceConnectionFactory, 
I made a sample project here. https://github.com/aronica/demo.
The stacktrace of my application is like below,

```org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'defaultRedisConnectionFactory' defined in class path resource [com/example/demo/configuration/RedisRepositoryConfig.class]: Invocation of init method failed;nested exception is java.lang.ClassCastException: io.lettuce.core.cluster.StatefulRedisClusterConnectionImpl cannot be cast to io.lettuce.core.api.StatefulRedisConnection
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.12.jar!/:5.3.12]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.12.jar!/:5.3.12]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.12.jar!/:5.3.12]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.12.jar!/:5.3.12]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.12.jar!/:5.3.12]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.12.jar!/:5.3.12]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.12.jar!/:5.3.12]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.12.jar!/:5.3.12]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.12.jar!/:5.3.12]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.12.jar!/:5.3.12]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.6.jar!/:2.5.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) [spring-boot-2.5.6.jar!/:2.5.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) [spring-boot-2.5.6.jar!/:2.5.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) [spring-boot-2.5.6.jar!/:2.5.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) [spring-boot-2.5.6.jar!/:2.5.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) [spring-boot-2.5.6.jar!/:2.5.6]
        at com.example.demo.DemoApplication.main(DemoApplication.java:10) [classes!/:0.0.1-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [demo-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [demo-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [demo-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) [demo-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
Caused by: java.lang.ClassCastException: io.lettuce.core.cluster.StatefulRedisClusterConnectionImpl cannot be cast to io.lettuce.core.api.StatefulRedisConnection
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.getSharedConnection(LettuceConnectionFactory.java:1089) ~[spring-data-redis-2.5.6.jar!/:2.5.6]
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.initConnection(LettuceConnectionFactory.java:543) ~[spring-data-redis-2.5.6.jar!/:2.5.6]
        at org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory.afterPropertiesSet(LettuceConnectionFactory.java:355) ~[spring-data-redis-2.5.6.jar!/:2.5.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.12.jar!/:5.3.12]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.12.jar!/:5.3.12]
        ... 24 common frames omitted```

**Comment by mp911de** [comment]
That is expected. When configuring to run with Redis Cluster, you will receive a `StatefulRedisClusterConnection` object (instead of `StatefulRedisConnection`) because Redis Cluster works differently from standalone Redis.

**Comment by aronica** [comment]
> That is expected. When configuring to run with Redis Cluster, you will receive a `StatefulRedisClusterConnection` object (instead of `StatefulRedisConnection`) because Redis Cluster works differently from standalone Redis.

So we could not use eagerInitialization with redis cluster mode? but we don't have a cluster mode LettuceConnectionFactory

**Comment by aronica** [comment]
> That is expected. When configuring to run with Redis Cluster, you will receive a `StatefulRedisClusterConnection` object (instead of `StatefulRedisConnection`) because Redis Cluster works differently from standalone Redis.

@mp911de please take a review again, I do not quite understand the reason on it, the workflow is when I enabled eagerInitialization in LettuceConnectionFactory, the call stack is (all code is in LettuceConnectionFactory.java)
```
afterPropertiesSet()->initConnection()->getSharedConnection()->getOrCreateSharedConnection().getConnection() 
```
as you said, getSharedConnection() always tried to cast StatefulRedisClusterConnection to StatefulRedisConnection when we are in redis cluster mode, if you think that's expected, then we should clarify it that `eagerInitialization` only works with none redis cluster mode in javadoc.

**Comment by mp911de** [comment]
Thanks for elaborating more. Initially, the ticket description was confusing so the fact that Spring Data Redis has a bug went unnoticed. I can confirm that there's a bug and we need to fix it.
