### ISSUE TITLE
Redis exception; nested exception is io.lettuce.core.RedisException: Connection closed

### ISSUE THREAD

**Issue by JiangYongKang** [spring-projects/spring-data-redis#2246]
Redis Version: 5.0.7
SpringBoot Version: 2.6.3

Whenever I shutdown my SpringBoot app, I get this exception
```Java
Disconnected from the target VM, address: '127.0.0.1:55326', transport: 'socket'
2022-01-26 22:50:49.681  INFO 12024 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-01-26 22:50:49.699  INFO 12024 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2022-01-26 22:50:49.702  WARN 12024 --- [cTaskExecutor-1] io.lettuce.core.RedisChannelHandler      : Connection is already closed
2022-01-26 22:50:49.704 ERROR 12024 --- [cTaskExecutor-1] ageListenerContainer$LoggingErrorHandler : Unexpected error occurred in scheduled task.

org.springframework.data.redis.RedisSystemException: Redis exception; nested exception is io.lettuce.core.RedisException: Connection closed
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:74) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:41) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.FallbackExceptionTranslationStrategy.translate(FallbackExceptionTranslationStrategy.java:42) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.convertLettuceAccessException(LettuceConnection.java:272) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.await(LettuceConnection.java:1063) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.lettuce.LettuceConnection.lambda$doInvoke$4(LettuceConnection.java:920) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.lettuce.LettuceInvoker$Synchronizer.invoke(LettuceInvoker.java:673) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.lettuce.LettuceInvoker$DefaultManyInvocationSpec.toList(LettuceInvoker.java:618) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.connection.lettuce.LettuceStreamCommands.xRead(LettuceStreamCommands.java:323) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.stream.DefaultStreamMessageListenerContainer.lambda$null$5(DefaultStreamMessageListenerContainer.java:263) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:223) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:190) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:177) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.stream.DefaultStreamMessageListenerContainer.lambda$getReadFunction$6(DefaultStreamMessageListenerContainer.java:262) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.stream.StreamPollTask.readRecords(StreamPollTask.java:166) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.stream.StreamPollTask.doLoop(StreamPollTask.java:147) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at org.springframework.data.redis.stream.StreamPollTask.run(StreamPollTask.java:132) ~[spring-data-redis-2.6.1.jar:2.6.1]
	at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: io.lettuce.core.RedisException: Connection closed
	at io.lettuce.core.protocol.DefaultEndpoint.notifyDrainQueuedCommands(DefaultEndpoint.java:679) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.lettuce.core.protocol.CommandHandler.channelInactive(CommandHandler.java:358) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.lettuce.core.protocol.RedisHandshakeHandler.channelInactive(RedisHandshakeHandler.java:89) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.lettuce.core.ChannelGroupListener.channelInactive(ChannelGroupListener.java:69) ~[lettuce-core-6.1.6.RELEASE.jar:6.1.6.RELEASE]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:813) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164) ~[netty-common-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[netty-common-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.73.Final.jar:4.1.73.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.73.Final.jar:4.1.73.Final]
	... 1 common frames omitted


Process finished with exit code 130
```

This is my code:

```Java
@Configuration
public class RedisSubscriptionConfig {

    @Resource
    private RedisStreamListener redisStreamListener;

    @Bean
    public Subscription subscription(RedisConnectionFactory redisConnectionFactory) {
        StreamMessageListenerContainer.StreamMessageListenerContainerOptions<String, ObjectRecord<String, String>>
                containerOptions = StreamMessageListenerContainer.StreamMessageListenerContainerOptions.builder()
                .pollTimeout(Duration.ofSeconds(1))
                .targetType(String.class)
                .build();
        StreamMessageListenerContainer<String, ObjectRecord<String, String>>
                listenerContainer = StreamMessageListenerContainer.create(redisConnectionFactory, containerOptions);
        Subscription subscription = listenerContainer.receive(
                StreamOffset.create("ORDERS", ReadOffset.lastConsumed()),
                redisStreamListener
        );
        listenerContainer.start();
        return subscription;
    }

}
```

```Java
@Slf4j
@Component
public class RedisStreamListener implements StreamListener<String, ObjectRecord<String, String>> {

    @Resource
    private RedisTemplate<String, Object> redisTemplate;

    @Override
    public void onMessage(ObjectRecord<String, String> message) {
        log.info("Receive Message: {}", message.getValue());
        redisTemplate.opsForStream().acknowledge("ORDERS", message);
    }

}
```

```Java
@Configuration
public class RedisConfig {

    @Bean
    public StringRedisTemplate stringRedisTemplate(RedisConnectionFactory redisConnectionFactory) {
        StringRedisTemplate stringRedisTemplate = new StringRedisTemplate();
        stringRedisTemplate.setConnectionFactory(redisConnectionFactory);
        return stringRedisTemplate;
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(redisConnectionFactory);
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        redisTemplate.setValueSerializer(new Jackson2JsonRedisSerializer<>(Object.class));
        redisTemplate.setHashKeySerializer(new StringRedisSerializer());
        redisTemplate.setHashValueSerializer(new Jackson2JsonRedisSerializer<>(Object.class));
        return redisTemplate;
    }

}
```

```text
spring.redis.host=127.0.0.1
spring.redis.port=6379
spring.redis.database=0
spring.redis.username=
spring.redis.password=
```
Can you tell me how to get rid of this exception message? Thank you so much!

**Comment by mp911de** [comment]
You need to shut down the `StreamMessageListenerContainer` prior to shutting down the application.

**Comment by Omraj-github** [comment]
Whenever I restart the service, I'm receiving the above error message. This message is occurring intermittently (sometimes thing works as expected). 
I've added `shutdownContainer` for `StreamMessageListenerContainer` as well. 
Here's my config:
package com.mvement.registry.voicecall.config;

import com.mvement.common.schema.Symbols;
import com.mvement.registry.voicecall.consumer.InboundVoiceCallRedisStreamConsumer;
import io.lettuce.core.SocketOptions;
import io.lettuce.core.TimeoutOptions;
import jakarta.annotation.PreDestroy;
import lombok.extern.slf4j.Slf4j;
import lombok.val;
import org.apache.commons.lang.exception.ExceptionUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.redis.connection.RedisConnectionFactory;
import org.springframework.data.redis.connection.RedisStandaloneConfiguration;
import org.springframework.data.redis.connection.lettuce.LettuceClientConfiguration;
import org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory;
import org.springframework.data.redis.connection.stream.Consumer;
import org.springframework.data.redis.connection.stream.MapRecord;
import org.springframework.data.redis.connection.stream.ReadOffset;
import org.springframework.data.redis.connection.stream.StreamOffset;
import org.springframework.data.redis.core.RedisTemplate;
import org.springframework.data.redis.serializer.StringRedisSerializer;
import org.springframework.data.redis.stream.StreamMessageListenerContainer;
import org.springframework.data.redis.stream.Subscription;

import java.time.Duration;
import java.util.List;
import java.util.Objects;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;

import static com.mvement.registry.voicecall.consumer.InboundVoiceCallRedisStreamConsumer.VOICE_CALL_INBOUND_GROUP;
import static com.mvement.registry.voicecall.consumer.InboundVoiceCallRedisStreamConsumer.VOICE_CALL_INBOUND_STREAM;


@Slf4j
@Configuration
public class InboundVoiceCallRedisStreamConfig {

    private static final String START = "start";
    private static final String STOP = "stop";
    private static final String CONSUMER = "consumer";
    private StreamMessageListenerContainer<String, MapRecord<String, String, String>> container;
    private final AtomicInteger recoveryAttempts = new AtomicInteger(0);
    private final List<Subscription> subscriptions = new CopyOnWriteArrayList<>();
    private static final ScheduledExecutorService singleThreadScheduledExecutor = Executors.newSingleThreadScheduledExecutor();

    @Value("${platform.redis.host}")
    private String redisHost;

    @Value("${platform.redis.port}")
    private int redisPort;

    @Value("${platform.redis.use.ssl}")
    private boolean useSsl;

    @Value("${platform.registry.redis.stream.consumer.count}")
    private int consumerCount;

    @Value("${platform.registry.redis.stream.consumer.polling.interval.ms}")
    private int redisStreamConsumerPollingIntervalInMs;

    @Value("${platform.registry.redis.stream.consumer.messages.per.interval.ms}")
    private int redisStreamConsumerMessagesPerPoll;

    @Value("${platform.registry.redis.stream.consumer.threads}")
    private int redisStreamConsumerThreads;

    @Autowired
    private ApplicationContext applicationContext;

    @Bean
    public RedisConnectionFactory redisConnectionFactory() {
        val config = new RedisStandaloneConfiguration(this.redisHost, this.redisPort);

        val clientOptions = io.lettuce.core.ClientOptions.builder()
                .autoReconnect(true) // ensures lettuce will reconnect if connection is dropped
                .disconnectedBehavior(io.lettuce.core.ClientOptions.DisconnectedBehavior.ACCEPT_COMMANDS)
                .pingBeforeActivateConnection(true)
                .timeoutOptions(TimeoutOptions.enabled())
                .socketOptions(SocketOptions.builder()
                        .keepAlive(true)
                        .tcpNoDelay(true)
                        .build())
                .build();

        val clientConfigBuilder = LettuceClientConfiguration.builder()
                .commandTimeout(Duration.ofMinutes(5)) // > this.redisStreamConsumerPollingIntervalInMs
                .clientOptions(clientOptions);

        if (useSsl) {
            clientConfigBuilder.useSsl();
        }

        val clientConfig = clientConfigBuilder.build();

        val factory = new LettuceConnectionFactory(config, clientConfig);
        factory.setShareNativeConnection(true);
        factory.setValidateConnection(true); // ensures connections are alive before use
        return factory;
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate(final RedisConnectionFactory factory) {
        val template = new RedisTemplate<String, Object>();
        template.setConnectionFactory(factory);
        template.setKeySerializer(new StringRedisSerializer());
        template.setValueSerializer(new StringRedisSerializer());
        template.setHashKeySerializer(new StringRedisSerializer());
        template.setHashValueSerializer(new StringRedisSerializer());
        return template;
    }

    @Bean(initMethod = START, destroyMethod = STOP)
    public StreamMessageListenerContainer<String, MapRecord<String, String, String>> streamMessageListenerContainer(final RedisConnectionFactory connectionFactory,
                                                                                                                    final RedisTemplate<String, Object> redisTemplate,
                                                                                                                    final InboundVoiceCallRedisStreamConsumer redisStreamConsumer) {
        var options = StreamMessageListenerContainer.StreamMessageListenerContainerOptions
                .builder()
                .pollTimeout(Duration.ofMillis(this.redisStreamConsumerPollingIntervalInMs))
                .batchSize(this.redisStreamConsumerMessagesPerPoll)
                .executor(Executors.newFixedThreadPool(this.redisStreamConsumerThreads))
                .errorHandler(error -> handleRedisStreamError(error, redisTemplate, redisStreamConsumer))
                .build();

        this.container = StreamMessageListenerContainer.create(connectionFactory, options);

        createConsumerGroupSafely(redisTemplate);
        registerSubscriptions(redisStreamConsumer);
        return this.container;
    }

    private void createConsumerGroupSafely(final RedisTemplate<String, Object> redisTemplate) {
        try {
            redisTemplate.opsForStream().createGroup(VOICE_CALL_INBOUND_STREAM, VOICE_CALL_INBOUND_GROUP);
            log.info("Created consumer group: {}", VOICE_CALL_INBOUND_GROUP);
        } catch (Exception e) {
            log.warn("Error creating consumer group for redis stream", e);
        }
    }

    private void registerSubscriptions(final InboundVoiceCallRedisStreamConsumer redisStreamConsumer) {
        subscriptions.clear(); // ensure clean slate
        for (var i = 1; i <= consumerCount; i++) {
            val consumerName = CONSUMER + Symbols.UNDERSCORE + i;
            log.info("Registering Redis consumer: {}", consumerName);

            val subscription = container.receive(
                    Consumer.from(VOICE_CALL_INBOUND_GROUP, consumerName),
                    StreamOffset.create(VOICE_CALL_INBOUND_STREAM, ReadOffset.lastConsumed()),
                    redisStreamConsumer
            );
            subscriptions.add(subscription);
        }
    }

    @PreDestroy
    public void shutdownContainer() {
        if (Objects.nonNull(container)) {
            log.info("Stopping StreamMessageListenerContainer before shutdown");

            while (container.isRunning()) {
                try {
                    Thread.sleep(50);
                } catch (InterruptedException ie) {
                    Thread.currentThread().interrupt();
                }
            }
            container.stop();

            // Wait for subscriptions to be inactive to avoid connection closed errors
            subscriptions.forEach(subscription -> {
                while (subscription.isActive()) {
                    try {
                        Thread.sleep(50);
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                    }
                }
            });

            if (container.isRunning()) {
                log.warn("Container still running after timeout during shutdown");
            }
        }
    }

    private void handleRedisStreamError(final Throwable error,
                                        final RedisTemplate<String, Object> redisTemplate,
                                        final InboundVoiceCallRedisStreamConsumer redisStreamConsumer) {
        if (isAppStopping() && isBenignConnectionClosed(error)) {
            log.info("Ignoring benign connection closed error during application shutdown: {}", error.getMessage());
            return;
        }

        log.error("Redis Stream error occurred: {}", error.getMessage(), error);

        // Short-circuit any recovery if context is closing/closed
        if (applicationContext instanceof ConfigurableApplicationContext ctx && !ctx.isActive()) {
            log.warn("Context is closing/closed, skipping recovery.");
            return;
        }

        int attempt = recoveryAttempts.incrementAndGet();
        long delay = Math.min(1000L * (1L << (attempt - 1)), 30000L); // exponential backoff

        if (attempt > 5) {
            log.warn("Recovery attempts are exceeded.");
            return;
        }
        log.warn("Scheduling recovery attempt {} in {} ms", attempt, delay);
        singleThreadScheduledExecutor.schedule(() -> {
            try {
                if (!(applicationContext instanceof ConfigurableApplicationContext execCtx) || !execCtx.isActive()) {
                    log.warn("ApplicationContext became inactive before recovery execution; aborting attempt {}.", attempt);
                    return;
                }

                log.info("Redis stream consumer recovery task starting (attempt {})...", attempt);
                recoverContainer(redisTemplate, redisStreamConsumer);
                log.info("Redis stream consumer recovery task completed (attempt {}).", attempt);
                recoveryAttempts.set(0);
            } catch (Throwable ex) {
                log.error("Exception in redis stream consumer recovery task (attempt {}): {}", attempt, ex.getMessage(), ex);
            }
        }, delay, TimeUnit.MILLISECONDS);
    }

    private void recoverContainer(final RedisTemplate<String, Object> redisTemplate,
                                  final InboundVoiceCallRedisStreamConsumer redisStreamConsumer) {
        try {
            log.info("Attempting Redis container recovery...");

            if (Objects.nonNull(container) && container.isRunning()) {
                container.stop();
                log.info("Stopped container");
            }

            subscriptions.forEach(sub -> {
                if (sub.isActive()) sub.cancel();
            });
            subscriptions.clear();

            Thread.sleep(1000);

            if (Objects.nonNull(container)) {
                container.start();
                log.info("Restarted Redis container");
                createConsumerGroupSafely(redisTemplate);
                registerSubscriptions(redisStreamConsumer); // re-register after restart
                log.info("Re-registered Redis subscriptions after recovery");
            }

            recoveryAttempts.set(0);
        } catch (Exception e) {
            log.error("Recovery failed: {}", e.getMessage(), e);
        }
    }

    private boolean isAppStopping() {
        return (applicationContext instanceof ConfigurableApplicationContext ctx) && !ctx.isActive();
    }

    private boolean isBenignConnectionClosed(Throwable t) {
        Throwable root = ExceptionUtils.getRootCause(t);
        return root instanceof io.lettuce.core.RedisException
                && String.valueOf(root.getMessage()).contains("Connection closed");
    }
}

Properties:
The properties:

platform.registry.redis.stream.messages.alive.time.ms=0
platform.registry.redis.stream.failed.message.retry.interval.time.ms=10000
platform.registry.redis.stream.failed.message.max.retry.count=0
platform.registry.redis.stream.consumer.polling.interval.ms=500
platform.registry.redis.stream.consumer.messages.per.interval.ms=4
platform.registry.redis.stream.consumer.threads=4
platform.registry.redis.stream.consumer.count=4
