### ISSUE TITLE
[Spring Data Redis 2.7.2 + Jedis 3.8.0] ClassCastException / redis.clients.jedis.JedisFactory : Error while QUIT 

### ISSUE THREAD

**Issue by rowi1de** [spring-projects/spring-data-redis#2382]
Using the following setup: https://start.spring.io/#!type=gradle-project&language=kotlin&platformVersion=2.7.2&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=data-redis

+ Adding "redis.clients:jedis" without a version, as managed by spring => resolves to 3.8.0 (matches what is documented here: https://docs.spring.io/spring-data/data-redis/docs/current/reference/html/#redis:connectors:jedis)

throws the following exception: 

```shell
java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class [B (java.util.ArrayList and [B are in module java.base of loader 'bootstrap')
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270)
	at redis.clients.jedis.BinaryJedis.quit(BinaryJedis.java:475)
	at redis.clients.jedis.JedisFactory.destroyObject(JedisFactory.java:160)
	at org.apache.commons.pool2.PooledObjectFactory.destroyObject(PooledObjectFactory.java:127)
	at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:611)
	at org.apache.commons.pool2.impl.GenericObjectPool.clear(GenericObjectPool.java:461)
	at org.apache.commons.pool2.impl.GenericObjectPool.close(GenericObjectPool.java:495)
	at redis.clients.jedis.util.Pool.closeInternalPool(Pool.java:136)
	at redis.clients.jedis.util.Pool.destroy(Pool.java:114)
	at org.springframework.data.redis.connection.jedis.JedisConnectionFactory.destroy(JedisConnectionFactory.java:478)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:213)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1163)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1156)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1106)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1075)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1021)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by mp911de** [comment]
It looks like a response was lingering on the Jedis connection from previous usage. A blank project as described above isn't able to reproduce the issue. The exception notice should not prevent the application shutdown but rather provide contextual details that the shutdown didn't work as expected and indicates a previous problem.

**Comment by rowi1de** [comment]
@mp911de thanks for the feedback, that’s true. I wasn’t able to reproduce the issue with a blank project

**Comment by mp911de** [comment]
FWIW, not saying there's not a problem, it's just something else that happens before the shutdown, and I'd be happy to fix it once we've identified the culprit.

**Comment by rowi1de** [comment]
@mp911de no that’s fine 👍🏻 Just noticed this issue is not actionable like this.
I was also not able to reproduce it in my producing code. And most exceptions hinted at incompatible versions with spring data & jedis (I assume broken dependency caching in my build)

**Comment by bbende** [comment]
I ran into this error this same error through the following scenario...

- Application is starting

- JedisSentinelPool gets created

- Logs start showing multiple occurrences of
```
[warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: stacksize: 1024k, guardsize: 0k, detached
```
- Start up continues trying to create a RedisMessageListenerContainer

- Eventually logs show
```
java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
```

- Application shutdown begins

- Destroy on the Jedis pool called and error from this issue is encountered

**Comment by mp911de** [comment]
According to the error message, there are not enough resources to start a new thread.

**Comment by bbende** [comment]
@mp911de yes the OOM about creating threads is a separate problem, but I am trying to give some information about how you could end up in a state that produces the ClassCastException since that needs to be resolved in your code

**Comment by kchristidis** [comment]
I am bumping into this issue deterministically on a private codebase. My suspicion is that this has something to do with the size of the Redis cluster, as I don't bump into this issue with smaller clusters.

## Dependencies

- spring-data-redis: 2.7.2
- jedis: 3.9.0 (but this also happens with 3.8.0)
- commons-pool2: 2.11.1

## Configuration settings

- `spring.redis.jedis.pool.max-active`=60
- `spring.redis.jedis.pool.max-idle`=60
- `spring.redis.jedis.pool.min-idle`=10

## What my code does

```java
public void scan(RedisClusterNode redisClusterNode, RedisClusterConnection redisClusterConnection, int scanLimit) { // scanLimit = 50
    ScanOptions scanOptions = ScanOptions.scanOptions().count(scanLimit).build();
    try (Cursor<byte[]> cursor = redisClusterConnection.scan(redisClusterNode, scanOptions)) {
      do {
        cursor.next();
      } while (cursor.hasNext());
    }
  }
```

This is how I set the `redisClusterNode` and `redisClousterConnection` fields before I pass them to the function:

```java
RedisConnection redisConnection = Objects.requireNonNull(stringRedisTemplate.getConnectionFactory()).getConnection();
if (redisConnection instanceof RedisClusterConnection) {
    RedisClusterConnection redisClusterConnection = Objects.requireNonNull(stringRedisTemplate.getConnectionFactory()).getClusterConnection();
    Iterable<RedisClusterNode> redisClusterNodes = redisClusterConnection.clusterGetNodes();
    StreamSupport.stream(redisClusterNodes.spliterator(), false).forEach(
        (redisClusterNode) -> { scan(redisClusterNode, redisClusterConnection, scanLimit);}
    );
} else {
// ...      
}
```

## How things fail

Shortly after I invoke this method, I will get the following:

```
[redis.clients.jedis.JedisFactory] [commons-pool-evictor] ERROR - <<JedisFactory>> Error while validating pooled Jedis object.
java.lang.ClassCastException: java.util.ArrayList cannot be cast to [B
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:270) ~[jedis-3.8.0.jar:?]
	at redis.clients.jedis.BinaryJedis.ping(BinaryJedis.java:384) ~[jedis-3.8.0.jar:?]
	at redis.clients.jedis.JedisFactory.validateObject(JedisFactory.java:214) ~[jedis-3.8.0.jar:?]
	at org.apache.commons.pool2.impl.GenericObjectPool.evict(GenericObjectPool.java:745) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.BaseGenericObjectPool$Evictor.run(BaseGenericObjectPool.java:160) ~[commons-pool2-2.11.1.jar:2.11.1]
	at org.apache.commons.pool2.impl.EvictionTimer$WeakRunner.run(EvictionTimer.java:113) ~[commons-pool2-2.11.1.jar:2.11.1]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_362]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
```

The timing of this exception differs. Sometimes it shows up right away, sometimes it takes a few seconds (and iterations of the cursor).

Note that the size of the shard is _big_: ~90M keys.

## Things I've tried without success

1. Running with only one thread active in the pool.
2. Running with an unlimited number of idle threads in the pool.
3. Setting `scanLimit` to `1`.

## Things I've tried successfully

1. Running against a much smaller cluster (each shard with hundreds of keys)

## 

@mp911de are there any diagnostics I could run on my end to help you debug this issue? Thanks in advance for your help.

**Comment by mp911de** [comment]
@kchristidis it sounds as if a cluster node connection was in use by two processes. I suggest monitoring `JedisCluster`'s node connection pool (`JedisClusterInfoCache.nodes`) while your `SCAN` is in progress. The node in the `ConnectionPool` should remain acquired while your scan cursor remains open. I suggest filing a new ticket as the title of the current ticket doesn't match your scenario.
