### ISSUE TITLE
DnsAddressResolverGroup failed to initialize and threw NoSuchMethodException when running native app in Linux environment

### ISSUE THREAD

**Issue by human-user** [spring-projects/spring-data-redis#2527]
I use spring boot 3.0 with spring-boot-starter-data-redis to build a native app in Ubuntu 22, it run success before. After spring-boot-starter-parent was updated from `3.0.2` to `3.0.3`,  native app ran fail because of `error creating bean with name 'lettuceClientResources'`. But it's still ok in win10.

It seems that DnsAddressResolverGroup failed to initialize because of  EpollDatagramChannel reflect not success. I am not sure the error caused by spring-data-redis or netty. 

Full stack log:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'lettuceClientResources': Instantiation of supplied bean failed
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1237) ~[demo:6.0.5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainFromSupplier(AbstractAutowireCapableBeanFactory.java:1211) ~[demo:6.0.5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1158) ~[demo:6.0.5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:562) ~[demo:6.0.5]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522) ~[demo:6.0.5]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[demo:6.0.5]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[demo:6.0.5]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[demo:6.0.5]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[demo:6.0.5]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[demo:6.0.5]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[demo:6.0.5]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[demo:6.0.5]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[demo:3.0.3]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[demo:3.0.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[demo:3.0.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[demo:3.0.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1304) ~[demo:3.0.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1293) ~[demo:3.0.3]
        at com.example.demo.DemoApplication.main(DemoApplication.java:10) ~[demo:na]
Caused by: java.lang.ExceptionInInitializerError: null
        at io.lettuce.core.resource.AddressResolverGroupProvider.<clinit>(AddressResolverGroupProvider.java:35) ~[na:na]
        at io.lettuce.core.resource.DefaultClientResources.<clinit>(DefaultClientResources.java:112) ~[demo:6.2.3.RELEASE]
        at org.springframework.boot.autoconfigure.data.redis.LettuceConnectionConfiguration.lettuceClientResources(LettuceConnectionConfiguration.java:71) ~[demo:na]
        at org.springframework.boot.autoconfigure.data.redis.LettuceConnectionConfiguration__BeanDefinitions.lambda$getLettuceClientResourcesInstanceSupplier$1(LettuceConnectionConfiguration__BeanDefinitions.java:41) ~[na:na]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:68) ~[demo:6.0.5]
        at org.springframework.util.function.ThrowingBiFunction.apply(ThrowingBiFunction.java:54) ~[demo:6.0.5]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.lambda$get$2(BeanInstanceSupplier.java:208) ~[na:na]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:59) ~[demo:6.0.5]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:47) ~[demo:6.0.5]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.invokeBeanSupplier(BeanInstanceSupplier.java:220) ~[na:na]
        at org.springframework.beans.factory.aot.BeanInstanceSupplier.get(BeanInstanceSupplier.java:208) ~[na:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.obtainInstanceFromSupplier(AbstractAutowireCapableBeanFactory.java:1226) ~[demo:6.0.5]
        ... 18 common frames omitted
Caused by: java.lang.IllegalArgumentException: Class EpollDatagramChannel does not have a public non-arg constructor
        at io.netty.channel.ReflectiveChannelFactory.<init>(ReflectiveChannelFactory.java:36) ~[na:na]
        at io.netty.resolver.dns.DnsNameResolverBuilder.channelType(DnsNameResolverBuilder.java:120) ~[na:na]
        at io.lettuce.core.resource.AddressResolverGroupProvider$DefaultDnsAddressResolverGroupWrapper.<clinit>(AddressResolverGroupProvider.java:57) ~[na:na]
        ... 30 common frames omitted
Caused by: java.lang.NoSuchMethodException: io.netty.channel.epoll.EpollDatagramChannel.<init>()
        at java.base@17.0.6/java.lang.Class.getConstructor0(DynamicHub.java:3585) ~[demo:na]
        at java.base@17.0.6/java.lang.Class.getConstructor(DynamicHub.java:2271) ~[demo:na]
        at io.netty.channel.ReflectiveChannelFactory.<init>(ReflectiveChannelFactory.java:34) ~[na:na]
        ... 32 common frames omitted

```

Add a reflect-config.json can solve this error which content like this: 
``` json
[
  {
    "condition": {
      "typeReachable": "io.netty.channel.epoll.Native"
    },
    "name":"io.netty.channel.epoll.EpollDatagramChannel",
    "allDeclaredConstructors": true
  }
]
```

**Comment by mp911de** [comment]
Please report this ticket against the netty project as we do not maintain reflection hints for 3rd party dependencies.
