### ISSUE TITLE
`GenericJackson2JsonRedisSerializer` can't deserialize previously serialized `Stream.toList()`

### ISSUE THREAD

**Issue by gcharondkt** [spring-projects/spring-data-redis#2697]
Hi there,

I'm facing an issue with the `GenericJackson2JsonRedisSerializer()` when using a `@Cacheable` annotation on a method returning a List<Integer> resulting of a `Stream.toList()` operation.

I can easily reproduce with the following unit test : 
```java
    List<Integer> toSerialize = Stream.of(2953).toList();

    @Test
    void test() {
        RedisSerializer<Object> serializer = RedisSerializer.json();

        var serialized = serializer.deserialize(serializer.serialize(new ArrayList<>(toSerialize))); // This is OK as the list is embedded in an ArrayList
        serialized = serializer.deserialize(serializer.serialize(toSerialize)); // EXCEPTION !!
    }
```

Please tell me if i'm doing something wrong.

SpringBoot version : 3.1.3

Stacktrace : 
```
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id '2953' as a subtype of `java.lang.Object`: no such class found
 at [Source: (byte[])"[2953]"; line: 1, column: 6]
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:2084)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1575)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:76)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:66)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:238)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializerNR.deserializeWithType(UntypedObjectDeserializerNR.java:115)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3874)
	at org.springframework.data.redis.serializer.JacksonObjectReader.lambda$create$0(JacksonObjectReader.java:54)
	at org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer.deserialize(GenericJackson2JsonRedisSerializer.java:250)
	... 70 more
```

**Comment by mp911de** [comment]
Would you mind attaching the full stack trace?

**Comment by gcharondkt** [comment]
Oh yes sorry i've forgotten, here it is.

In debug mode, I can see a difference between the two serialized values : 
* With ArrayList : ["java.util.ArrayList",[2953]]
* Without : [2953]

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id '2953' as a subtype of `java.lang.Object`: no such class found
 at [Source: (byte[])"[2953]"; line: 1, column: 6]
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.invalidTypeIdException(DeserializationContext.java:2084)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1575)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver._typeFromId(ClassNameIdResolver.java:76)
	at com.fasterxml.jackson.databind.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:66)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:238)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializerNR.deserializeWithType(UntypedObjectDeserializerNR.java:115)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4825)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3874)
	at org.springframework.data.redis.serializer.JacksonObjectReader.lambda$create$0(JacksonObjectReader.java:54)
	at org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer.deserialize(GenericJackson2JsonRedisSerializer.java:250)
	... 70 more
```

**Comment by mp911de** [comment]
The difference between the two values is that the `ArrayList` variant is non-final while `Stream.toList()` produces a final and private type `ImmutableCollections$ListN`. The typing mechanism skips adding type hints if the type is `final` and originates from the `java.` namespace as these types are typically private and cannot be accessed via reflection.

On the other side, we attempt to preserve custom collection types when reading arrays. Unfortunately, all we have to read the serialized value is `java.lang.Object` as type hint and we need to determine the type to read, so we default to parse the type hint.


The suggested workaround is to wrap the resulting value in a value object instead of caching the top-level value. Paging @christophstrobl for further insights.

**Comment by gcharondkt** [comment]
I have implemented a workaround like this : 
```java
@Cacheable
public List<Integer> getValue() {
    return new ArrayList<>(result.stream().toList());
}
```

Instead of this : 
```java
@Cacheable
public List<Integer> getValue() {
    return result.stream().toList();
}
```


But still, i thought it was a good idea to open an issue because the error is difficult to detect : the execution was not stopped by any exception, the only impact is that the `@Cacheable` was not working, resulting in many unexpected API calls.


Also, even if I understand why this is raising an error, in my opinion a serializer should not serialize something that he won't be able to deserialize, don't you think ?

**Comment by mp911de** [comment]
> Also, even if I understand why this is raising an error, in my opinion a serializer should not serialize something that he won't be able to deserialize, don't you think ?

I fully agree, I just do not have an idea how to tackle top-level arrays as we don't seem to have sufficient hooks to either always or never enable typing.

**Comment by jxblum** [comment]
I reproduced this problem in the following test case method that I am currently adding to the `GenericJackson2JsonRedisSerializerUnitTests` class in Spring Data Redis to debug and explore possible solutions further.

```java
@Test // GH-2697
void serializingDeserializingIntegerListIsHandledCorrectly() {

    GenericJackson2JsonRedisSerializer redisSerializer = 
        new GenericJackson2JsonRedisSerializer();

    List<Integer> integers = Stream.of(2953).toList();
    //List<Integer> integers = List.of(2953);
    //List<Integer> integers = new ArrayList<>(Stream.of(2953).toList());
    //List<Integer> integers = new LinkedList<>(List.of(2953));

    Object deserializedIntegers = 
        redisSerializer.deserialize(redisSerializer.serialize(integers));

    assertThat(deserializedIntegers)
        .isInstanceOf(List.class)
        .asInstanceOf(InstanceOfAssertFactories.type(List.class))
        .extracting(list -> list.get(0))
        .isEqualTo(2953);

    deserializedIntegers = 
        redisSerializer.deserialize(redisSerializer.serialize(deserializedIntegers));

    assertThat(deserializedIntegers)
        .isInstanceOf(List.class)
        .asInstanceOf(InstanceOfAssertFactories.type(List.class))
        .extracting(list -> list.get(0))
        .isEqualTo(2953);
}
```

Clearly, you can see that I am playing around with different combinations.

What many developers fail to realize is that the `Collection` types returned by operations like `Stream.toList()`, or `List.of(..)`, and even `Arrays.asList(..)`, which seemingly is benign when looking at the source code, because `Arrays.asList(..)` returns an "`ArrayList`" even, though it is NOT a `java.util.ArrayList`, but rather a `java.util.Arrays.ArrayList` instead! So, these are NOT typical, `public` (and standard) `Collection` types in the `java.util` package that developers are familiar with and use most often (they are "internal").

This leads to many surprises when users try to use the `List`, such as in a mutating manner, which they are not. These `Collections` effectively are read-only once created.

Additionally, as @mp911de pointed out, these `Collection` types are `private`, or often `package private`, such as the (internal) `Collection` types in the `java.util.Collections` class.

I agree with Mark. I think we have room for improvement, but I am not exactly certain what that is yet. I will continue to think on this next week and talk with both @mp911de and @christophstrobl about possible ideas.

**Comment by NathanD001** [comment]
The issue is that ImmutableListN is a final class
```java
    @jdk.internal.ValueBased
    static final class ListN<E> extends AbstractImmutableList<E>
            implements Serializable
``java

it does work if you use `ObjectMapper.DefaultTyping.EVERYTHING` however I'd rather not use that solution, and Jackson is removing it in 3.0 
https://github.com/FasterXML/jackson-databind/blob/2.17/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L227

I also found an alternative using Guava ImmutableList instead of Java ImmutableListN  and `jackson-datatype-guava`  

`.collect(ImmutableList.toImmutableList())` intead of `.toList()`

then add `cacheObjectMapper.registerModule(new GuavaModule()); `

I do wish it would work with out either of these workarounds. Does anyone else have suggestions?

**Comment by liran2000** [comment]
agree with comments above, the issue affects runtime, a fix without work-arounds can help.

Unit test to show it, similar to as posted above:
```
@Test
    void genericJackson2JsonRedisSerializerTest() {
        List<Integer> list = List.of(1,2);

        // direct ObjectMapper - success
        ObjectMapper mapper = new ObjectMapper();
        String json = mapper.writeValueAsString(list);
        Object object = mapper.readValue(json, Object.class);
        assertEquals(list, object);

        list = new ArrayList<>();
        list.add(1);
        list.add(2);

        GenericJackson2JsonRedisSerializer serializer = new GenericJackson2JsonRedisSerializer();

        // new ArrayList<>() - success
        byte[] serialized = serializer.serialize(list);
        serializer.deserialize(serialized);
        assertEquals(list, serializer.deserialize(serialized));

        // List.of - failure
        list = List.of(1,2);
        serialized = serializer.serialize(list);
        serializer.deserialize(serialized);
        assertEquals(list, serializer.deserialize(serialized));

        // toList() - failure
        list = list.stream().toList();
        serialized = serializer.serialize(list);
        serializer.deserialize(serialized);
        assertEquals(list, serializer.deserialize(serialized));
    }
```

**Comment by keepConcentration** [comment]
I ran into the same deserialization issue with `Stream.toList()` and `List.of()`, and was able to work around it by introducing a custom `TypeResolver` that forces type information for all `Collection` and `Map` types:

```java
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.jsontype.PolymorphicTypeValidator;
import com.fasterxml.jackson.databind.jsontype.impl.StdTypeResolverBuilder;
import org.junit.jupiter.api.Test;
import org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer;

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

public class ImmutableListSerializationTest {

    @Test
    void testSerialization() {
        ObjectMapper objectMapper = new ObjectMapper();

        CustomTypeResolver typeResolver = new CustomTypeResolver(
                ObjectMapper.DefaultTyping.NON_FINAL,
                objectMapper.getPolymorphicTypeValidator());

        StdTypeResolverBuilder initializedResolver = typeResolver.init(JsonTypeInfo.Id.CLASS, null);
        initializedResolver = initializedResolver.inclusion(JsonTypeInfo.As.PROPERTY);
        objectMapper.setDefaultTyping(initializedResolver);

        GenericJackson2JsonRedisSerializer serializer = new GenericJackson2JsonRedisSerializer(objectMapper);

        // new ArrayList<>() - success
        List<Integer> list = new ArrayList<>();
        list.add(1);
        list.add(2);
        byte[] serialized = serializer.serialize(list);
        assertEquals(list, serializer.deserialize(serialized));

        // List.of - success
        list = List.of(1, 2);
        serialized = serializer.serialize(list);
        assertEquals(list, serializer.deserialize(serialized));

        // toList() - success
        list = Stream.of(1, 2).toList();
        serialized = serializer.serialize(list);
        assertEquals(list, serializer.deserialize(serialized));
    }

    static class CustomTypeResolver extends ObjectMapper.DefaultTypeResolverBuilder {

        public CustomTypeResolver(ObjectMapper.DefaultTyping t, PolymorphicTypeValidator ptv) {
            super(t, ptv);
        }

        @Override
        public boolean useForType(JavaType t) {
            Class<?> rawClass = t.getRawClass();
            if (Collection.class.isAssignableFrom(rawClass) || Map.class.isAssignableFrom(rawClass)) {
                return true;
            }

            return super.useForType(t);
        }
    }
}

```

**Comment by jewoodev** [comment]
Tracing this a bit further: the missing hint only ever shows up at the very root. A root value is typed against its concrete runtime class, which `useForType` deliberately skips for `final` `java.*` collections (`Stream.toList()`/`List.of()` → `ImmutableCollections$ListN`), so it serializes as a bare `[2953]`. A collection's elements, by contrast, are serialized against an `Object` declared type and keep their hint — e.g. `List.of(List.of(1, 2))` serializes the inner lists as `["java.util.ImmutableCollections$List12", [1, 2]]`. On read, the bare root array is then misread as `[typeId, value]`, which is the `InvalidTypeIdException`.

One angle that sidesteps the "always vs. never enable typing" dilemma is to leave the serialized form untouched and recover on read. When `GenericJackson2JsonRedisSerializer.deserialize(..)` hits that `InvalidTypeIdException` on a root array, it could fall back to decomposing the root array node and reading each element through the same default-typing `ObjectMapper` (`treeToValue(element, Object.class)`), rather than letting the root array go through the type-wrapper deserializer. Because the gap exists only at the root, nested `@class` hints are still honored — a local prototype round-trips `List.of(..)`/`Stream.toList()` and brings nested objects back as their real type rather than a `LinkedHashMap`. Notably this can't be a plain `deserialize(source, List.class)` retry (`List` still participates in default typing), nor a "disable default typing" read (that one drops the nested hints).

This is intentionally a best-effort fallback that engages only on failure, so it changes nothing that works today and leaves the genuinely ambiguous case (a first element that *does* resolve to a real class, e.g. `["java.lang.String", "hello"]`) untouched. The upside is that the wire format stays the same, so values already cached as `[..]` become readable without re-serialization. I would be happy to put together a focused PR with round-trip tests for `List.of(..)`, `Stream.toList()`, and nested element types if this direction seems reasonable — please let me know if you'd prefer a different approach.
