### ISSUE TITLE
BoundHashOperations referenced from a method is not visible from class loader

### ISSUE THREAD

**Issue by sthakore-atlassian** [spring-projects/spring-data-redis#2772]
Hello,

We moved from spring-boot 2 to spring boot 3 and upgraded the spring-data-redis. We are facing an issue with this version with below error stack trace at runtime. 

```
java.lang.IllegalArgumentException: org.springframework.data.redis.core.BoundHashOperations referenced from a method is not visible from class loader
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.ensureVisible(Unknown Source)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.validateProxyInterfaces(Unknown Source)
	at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Unknown Source)
	at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Unknown Source)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(Unknown Source)
	at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(Unknown Source)
	at java.base/java.lang.reflect.Proxy.getProxyConstructor(Unknown Source)
	at java.base/java.lang.reflect.Proxy.newProxyInstance(Unknown Source)
	at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:123)
	at org.springframework.aop.framework.JdkDynamicAopProxy.getProxy(JdkDynamicAopProxy.java:115)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:97)
	at org.springframework.data.redis.core.BoundOperationsProxyFactory.createProxy(BoundOperationsProxyFactory.java:73)
	at org.springframework.data.redis.core.RedisTemplate.boundHashOps(RedisTemplate.java:985)
```

Below is the function we are trying to call

```java
var hashOperations = redisTemplate.<Integer, String>boundHashOps(getEtagKey(referenceId));
```

**Comment by mp911de** [comment]
Can you provide a reproducer? Attempting to reproduce failed with a Spring Boot 3 app:

```java
@Bean
CommandLineRunner clr(RedisTemplate<String, String> template) {
	return args -> {
		template.boundHashOps("my-key").entries();
	};
}
```

**Comment by sthakore-atlassian** [comment]
Hey @mp911de Thanks for your quick response.

Spring Boot : 3.1.2
Spring Data Redis : 3.1.2

It's failing here in first line where we call `boundHashOps`

```
var hashOperations = redisTemplate.<Integer, String>boundHashOps("abc");

hashOperations.put(8463,"xyz");
hashOperations.expire(Duration.ofHours(6));
```

**Comment by mp911de** [comment]
Still cannot reproduce. Can you provide please a minimal reproducer? Using https://start.spring.io will get you started.

**Comment by jxblum** [comment]
Is this the full Stack Trace? I suspect not. 

Also, in what context is your Spring application running? Is this a Web application inside Apache Tomcat, Eclipse Jetty, or some other container environment?

Are you using a custom `ClassLoader`, perhaps?

What dependencies are on your Spring application classpath?

> NOTE: I only ask the last question because some users have experienced certain anomalies when other libraries, such as Redisson, are also on their Spring application classpath. I am not saying Redisson is the issue or that this is your issue in particular, but having a snapshot of your dependencies might shed some light on the problem. Therefore...

Are you by chance using Java's module system and modulepath?

The jump from Spring Boot 2 to Spring Boot 3 also suggests that you moved from (possibly, as early as) Java 8 to minimally, Java 17.

Since this is not readily reproducible, it is unlikely to be a specific problem with Spring Data Redis, therefore a small, self-contained reproducer will help us help you.

Thanks.

**Comment by jxblum** [comment]
NOTE: Upon closer inspection, given the "ETag" reference from your snippet of code above, I gather this is a Web application.

**Comment by jxblum** [comment]
As @mp911de did above, I also wrote a quick [test class](https://github.com/jxblum/redis-experiments/blob/spring-data-redis-issue-2772/spring-data-redis-experiments/src/test/java/io/vmware/spring/data/redis/tests/operations/hash/RedisHashOperationsIntegrationTests.java#L54) based on this issue for a sanity check.

You an see the dependencies of my (test) classpath [here](https://github.com/jxblum/redis-experiments/blob/spring-data-redis-issue-2772/spring-data-redis-experiments/pom.xml#L31-L51) along with [this](https://github.com/jxblum/redis-experiments/blob/spring-data-redis-issue-2772/pom.xml#L45-L106).

This test passes as expected and I am using Spring Boot `3.1.5` (which pulls in Spring Data Redis `3.1.5`); see [here](https://github.com/jxblum/redis-experiments/blob/spring-data-redis-issue-2772/pom.xml#L9-L11).

**Comment by app2smile** [comment]
Hello, I have encountered a similar issue as this:
```
org.springframework.data.redis.core.BoundValueOperations referenced from a method is not visible from class loader: 'app'
```

environment:
```
jdk21
spring boot 3.2.6
caffeine
```

Detailed description:

When I ran the following code inside the Docker container, an error occurred I am unable to reproduce this issue when running in a local environment I don't know what caused this problem
```
@SpringBootApplication
public class CaffeineDemoApplication implements CommandLineRunner {
    @Autowired
    private StringRedisTemplate stringRedisTemplate;

    @Override
    public void run(String... args) throws Exception {
        LoadingCache<String, String> cache = Caffeine.newBuilder()
                .refreshAfterWrite(Duration.ofSeconds(5))
                .build(key -> {
                    // do something
                    // ...
                    stringRedisTemplate.boundValueOps(key).set("1");
                    // ...
                    return "any";
                });
        cache.get("1");

        // error
        // java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: org.springframework.data.redis.core.BoundValueOperations referenced from a method is not visible from class loader: 'app'
        cache.refresh("1");
    }

    public static void main(String[] args) {
        SpringApplication.run(CaffeineDemoApplication.class, args);
    }
}
```

Reproduction steps:
1. Modify the Redis configuration in application.yml
2. maven install
3. docker build -t demo:v1 .
4.  docker run --rm --net=host demo:v1

[demo.zip](https://github.com/spring-projects/spring-data-redis/files/15480789/demo.zip)

**Comment by jianxia612** [comment]
This Exception Because CompletableFuture，Executor Paramters，Use ForkJoinPool

[https://stackoverflow.com/questions/49113207/completablefuture-forkjoinpool-set-class-loader](https://link.segmentfault.com/?enc=XAd4a7ZLXvOmKFDx0g4OHg%3D%3D.gEPfzrMwAQyWhcA5cHuZBtkPqnkj5N1rDkgrSB1Ci6UibLjWYDdHN8NeEelctiweJ5EMIPcvsUiaxjEKuND58p0622AVxTvMOQIX%2B3Oe17bLLvk1O9l3%2B8BuQx5cQ3U7)

I Use custom Executor ThreadPool solve this exception
