### ISSUE TITLE
Cannot set `notify-keyspace-events` to empty string

### ISSUE THREAD

**Issue by marcusdacoregio** [spring-projects/spring-data-redis#2798]
The [Redis documentation](https://redis.io/docs/manual/keyspace-notifications/#:~:text=Setting%20the%20parameter%20to%20the%20empty%20string%20disables%20notifications.) says (emphasis by me):

> Notifications are enabled using the notify-keyspace-events of redis.conf or via the CONFIG SET.
**Setting the parameter to the empty string disables notifications.**

However, when I try to do:

```java
connection.serverCommands().setConfig("notify-keyspace-events", "").then()
```

An error is thrown:

```
Caused by: java.lang.IllegalArgumentException: Value must not be null or empty
	at org.springframework.util.Assert.hasText(Assert.java:240)
	at org.springframework.data.redis.connection.lettuce.LettuceReactiveServerCommands.setConfig(LettuceReactiveServerCommands.java:133)
```

Is this expected?

**Comment by mp911de** [comment]
Thanks for the report. This is indeed a bug on our side with the Lettuce driver. The Jedis implementation handles this already properly.
