### ISSUE TITLE
GraalVM - o.lettuce.core.resource.ClientResources.shutdown() invoked without it being registered for runtime reflection

### ISSUE THREAD

**Issue by NicklasWallgren** [spring-projects/spring-data-redis#2827]
`ClientResources#shutdown` is missing runtime reflection hints.

I've been using the following configuration to fix the issue locally.
```
  {
    "name":"io.lettuce.core.resource.ClientResources",
    "queryAllDeclaredMethods":true,
    "queryAllPublicMethods":true,
    "methods":[{"name":"shutdown","parameterTypes":[] }]
  }
```

Stacktrace
```
[SpringApplicationShutdownHook] WARN  o.s.b.f.s.DisposableBeanAdapter transactionId:  traceId:  - Failed to invoke custom destroy method 'shutdown' on bean with name 'lettuceClientResources'
org.graalvm.nativeimage.MissingReflectionRegistrationError: The program tried to reflectively invoke method public abstract io.netty.util.concurrent.Future io.lettuce.core.resource.ClientResources.shutdown() without it being registered for runtime reflection. Add public abstract io.netty.util.concurrent.Future io.lettuce.core.resource.ClientResources.shutdown() to the reflection metadata to solve this problem. See https://www.graalvm.org/latest/reference-manual/native-image/metadata/#reflection for help.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.MissingReflectionRegistrationUtils.forQueriedOnlyExecutable(MissingReflectionRegistrationUtils.java:72)
        at java.base@21.0.1/java.lang.reflect.Method.acquireMethodAccessor(Method.java:77)
        at java.base@21.0.1/java.lang.reflect.Method.invoke(Method.java:577)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:316)
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:249)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1200)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1193)
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1125)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1086)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1037)
        at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
```

**Comment by mp911de** [comment]
Care to provide a reproducer? Building an image for a vanilla Spring Boot 3.1/3.2 app and running the binary doesn't produce the issue.

**Comment by NicklasWallgren** [comment]
> Care to provide a reproducer? Building an image for a vanilla Spring Boot 3.1/3.2 app and running the binary doesn't produce the issue.

Hmm, I couldn't reproduce the issue with Spring Boot 3.2.1 only in 3.2.0.  I guess we can close this one, thanks!
