### ISSUE TITLE
DefaultStreamMessageListenerContainer can't close

### ISSUE THREAD

**Issue by sanwzzz** [spring-projects/spring-data-redis#2939]
When I close Spring, it outputs the following information to the stack.
```
2024-07-11 19:57:52.900 [ERROR] [SimpleAsyncTaskExecutor-5] [rContainer$LoggingErrorHandler] Unexpected error occurred in scheduled task
org.springframework.dao.InvalidDataAccessApiUsageException: Redisson is shutdown
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:52)
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35)
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:40)
	at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:208)
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:203)
	at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:374)
	at org.redisson.spring.data.connection.RedissonConnection.write(RedissonConnection.java:740)
	at org.redisson.spring.data.connection.RedissonStreamCommands.xReadGroup(RedissonStreamCommands.java:655)
	at org.springframework.data.redis.stream.DefaultStreamMessageListenerContainer.lambda$getReadFunction$3(DefaultStreamMessageListenerContainer.java:236)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:396)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:363)
	at org.springframework.data.redis.core.RedisTemplate.execute(RedisTemplate.java:350)
	at org.springframework.data.redis.stream.DefaultStreamMessageListenerContainer.lambda$getReadFunction$4(DefaultStreamMessageListenerContainer.java:235)
	at org.springframework.data.redis.stream.StreamPollTask.readRecords(StreamPollTask.java:146)
	at org.springframework.data.redis.stream.StreamPollTask.doLoop(StreamPollTask.java:127)
	at org.springframework.data.redis.stream.StreamPollTask.run(StreamPollTask.java:112)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.redisson.RedissonShutdownException: Redisson is shutdown
	at org.redisson.connection.ServiceManager.lambda$shutdownFutures$2(ServiceManager.java:362)
	at java.base/java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4709)
	at java.base/java.util.Collections$SetFromMap.forEach(Collections.java:5944)
	at org.redisson.connection.ServiceManager.shutdownFutures(ServiceManager.java:362)
	at org.redisson.connection.MasterSlaveConnectionManager.shutdown(MasterSlaveConnectionManager.java:505)
	at org.redisson.connection.MasterSlaveConnectionManager.shutdown(MasterSlaveConnectionManager.java:490)
	at org.redisson.Redisson.shutdown(Redisson.java:1121)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:316)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:249)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:587)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:559)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1202)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:520)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1195)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1186)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1147)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:174)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1093)
	at org.springframework.boot.SpringApplicationShutdownHook.closeAndWait(SpringApplicationShutdownHook.java:145)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.SpringApplicationShutdownHook.run(SpringApplicationShutdownHook.java:114)
	... 1 common frames omitted
```
And my StreamMessageListenerContainer
![Clip_2024-07-11_20-09-27](https://github.com/spring-projects/spring-data-redis/assets/39424325/174a9adf-d927-4222-bbbe-6727f6db9817)

**Comment by sanwzzz** [comment]
And Listenet. is triggered every time, even if there is no data in the stream
![Clip_2024-07-11_20-13-00](https://github.com/spring-projects/spring-data-redis/assets/39424325/2b327c90-25f9-4842-9954-86073003dceb)

**Comment by sanwzzz** [comment]
so, Is it the same problem as #2261 ?

**Comment by christophstrobl** [comment]
@sanwzzz thank you for reaching out. Please do not use images to provide issue details, but take the time to provide a complete [minimal sample](https://stackoverflow.com/help/minimal-reproducible-example) (something that we can unzip or git clone, build, and deploy) that reproduces the problem. 

However, the Redisson driver is not directly supported by the data-redis project, and though the issue sounds similar to the existing one you linked, I'll be therefore closing this issue.
