### ISSUE TITLE
[Bug] GenericJackson2JsonRedisSerializer cannot deserialize values for ObjectMappers with custom JsonFactory

### ISSUE THREAD

**Issue by housevenn** [spring-projects/spring-data-redis#2981]
We create RedisCacheConfiguration with value serializer like this:
```
        RedisSerializer valueSerializer = new GenericJackson2JsonRedisSerializer(new ObjectMapper(new MessagePackFactory()));
        RedisCacheConfiguration redisCacheConfig = RedisCacheConfiguration.serializeValuesWith(RedisSerializationContext.SerializationPair.fromSerializer(valueSerializer));

```
It uses an ObjectMapper with a custom JsonFactory (MessagePackFactory). Serialization works correctly, but deserialization encounters the following exception:

> com.fasterxml.jackson.core.JsonParseException: Unexpected character ('²' (code 178)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
>  at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 1]
> 	at com.fasterxml.jackson.core.JsonParser._constructReadException(JsonParser.java:2643)
> 	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:685)
> 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2750)
> 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:867)
> 	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:753)
> 	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4934)
> 	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3294)
> 	at org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer$TypeResolver.resolveType(GenericJackson2JsonRedisSerializer.java:363)
> 	at org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer.resolveType(GenericJackson2JsonRedisSerializer.java:337)
> 	at org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer.deserialize(GenericJackson2JsonRedisSerializer.java:304)
> 	at org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer.deserialize(GenericJackson2JsonRedisSerializer.java:276)
> 	at com.coupang.storageservice.redis.spring.data.sdk.serializer.GzipRedisSerializer.deserialize(GzipRedisSerializer.java:54)
> 	at org.springframework.data.redis.serializer.DefaultRedisElementReader.read(DefaultRedisElementReader.java:46)
> 	at org.springframework.data.redis.serializer.RedisSerializationContext$SerializationPair.read(RedisSerializationContext.java:277)
> 	at org.springframework.data.redis.cache.RedisCache.deserializeCacheValue(RedisCache.java:386)
> 	at org.springframework.data.redis.cache.RedisCache.lookup(RedisCache.java:209)

The error happens on [this line](https://github.com/spring-projects/spring-data-redis/blob/bfa62bf31d591a0eb51cb6ba20c6f8d4f5bddd9f/src/main/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.java#L304) at resolveType. The cause is that TypeResolver uses a [default ObjectMapper](https://github.com/spring-projects/spring-data-redis/blob/bfa62bf31d591a0eb51cb6ba20c6f8d4f5bddd9f/src/main/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.java#L346) which would throw exception [here](https://github.com/spring-projects/spring-data-redis/blob/bfa62bf31d591a0eb51cb6ba20c6f8d4f5bddd9f/src/main/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.java#L363) when the value is serialized by our ObjectMapper with custom JsonFactory as shown above. The default ObjectMapper uses [MappingJsonFactory](https://github.com/joansmith/jackson-databind/blob/230a19d527df7dc0c05017429bcb7aa1cbbe41ef/src/main/java/com/fasterxml/jackson/databind/ObjectMapper.java#L519) in comparison.

Solution: when creating the TypeResolver [here](https://github.com/spring-projects/spring-data-redis/blob/ed7bc0814cffe6a8d3ac4047b1492d488c47d3bc/src/main/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.java#L174), we should use the ObjectMapper which was passed in [here](https://github.com/spring-projects/spring-data-redis/blob/ed7bc0814cffe6a8d3ac4047b1492d488c47d3bc/src/main/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.java#L149), and store it on the TypeResolver to use. Or at least make that an option so we can use it to avoid the deserialization error. I have test that it can fix the deserialization issue, but not sure if there is any other implication.

FYI, our code was working fine with spring-data-redis 2.7.x but encountered this issue now as we are upgrading to spring-data-redis 3. It's because of [this commit](https://github.com/spring-projects/spring-data-redis/pull/2332/files#diff-f69375baacf0f4229891dc9717f7086f8398fe2e66f7968efc079d1c0ca0b8c2) which changed the deserialization function and added resolveType.

**Comment by mp911de** [comment]
We're using a pristine `ObjectMapper` in `TypeResolver` as reading the type into `JsonNode` fails due to polymorphing typing restrictions.

I suggest that you explore options that let our test suite pass while you're able to address your issue.

**Comment by housevenn** [comment]
Thanks for the explanation. So it looks like using ObjectMapper which has enabled typing (like [this](https://github.com/spring-projects/spring-data-redis/blob/feda7dcf5b0a2f451d8ad8b2b45c087c1af92bce/src/test/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializerUnitTests.java#L169)) will not work, right?

Since our mapper does not enable it, it will still work. I am thinking we can expose a public function to support setting the custom mapper in type resolver (and add a comment that mappers which has enabled typing will not work). 

I have a [draft PR](https://github.com/spring-projects/spring-data-redis/pull/2991/files). I don't think it is a clean approach, but have not come up with a better alternative. Could you help take a look?

**Comment by mp911de** [comment]
Thanks for looking into it. We indeed are looking for an approach that doesn't require additional configuration. 

I created an approach by using `JsonParser` with `JsonNodeDeserializer` directly as alternative.

**Comment by housevenn** [comment]
Awesome. I have closed my draft PR and will wait for yours. Thanks!
